
package ci;

import java.awt.Graphics;
import java.util.Iterator;
import java.util.TreeMap;

/**
 *
 * @author peter
 */
public class CIChartSetupPlotPanel extends javax.swing.JPanel {

 CrInstrument instrument;
 TreeMap itemTM=new TreeMap();
  public CIChartSetupPlotPanel(CrInstrument instrument) {
    initComponents();
    this.instrument=instrument;
  }
  

protected void paintComponent(Graphics g) {

}

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")

    private void initComponents() {

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }

  private void formKeyPressed(java.awt.event.KeyEvent evt) {

  }

  private void formMouseClicked(java.awt.event.MouseEvent evt) {

  }

  private void formMouseDragged(java.awt.event.MouseEvent evt) {

  }

}