
package ci;

import java.awt.Color;
import java.util.Iterator;
import javax.swing.DefaultListModel;
import javax.swing.JColorChooser;
import y.ylib.ylib;

/**
 *
 * @author peter
 */
public class CICurveSetupPanel extends javax.swing.JPanel {

  CrInstrument instrument;
  DefaultListModel curveListModel = new DefaultListModel();
    public CICurveSetupPanel(CrInstrument instrument) {
        initComponents();
        this.instrument=instrument;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void initComponents() {

        jPanel92 = new javax.swing.JPanel();
        jLabel169 = new javax.swing.JLabel();
        jComboBox40 = new javax.swing.JComboBox();
        jLabel170 = new javax.swing.JLabel();
        jComboBox50 = new javax.swing.JComboBox();
        jLabel171 = new javax.swing.JLabel();
        jComboBox51 = new javax.swing.JComboBox();
        jScrollPane10 = new javax.swing.JScrollPane();
        curveList = new javax.swing.JList(curveListModel);
        jLabel109 = new javax.swing.JLabel();
        jPanel95 = new javax.swing.JPanel();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jPanel102 = new javax.swing.JPanel();
        jLabel103 = new javax.swing.JLabel();
        jComboBox33 = new javax.swing.JComboBox();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jPanel105 = new javax.swing.JPanel();
        jLabel106 = new javax.swing.JLabel();
        jComboBox34 = new javax.swing.JComboBox();
        jLabel89 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabel172 = new javax.swing.JLabel();
        jComboBox52 = new javax.swing.JComboBox();
        jPanel107 = new javax.swing.JPanel();
        jLabel144 = new javax.swing.JLabel();
        jLabel145 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();

        setLayout(null);

        jPanel92.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel169.setFont(jLabel169.getFont());
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("ci/Bundle"); 
        jLabel169.setText(bundle.getString("CrInstrument.jLabel169.text")); 
        jPanel92.add(jLabel169);

        jComboBox40.setEditable(true);
        jComboBox40.setFont(jComboBox40.getFont());
        jComboBox40.setPreferredSize(new java.awt.Dimension(204, 25));
        jComboBox40.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox40ItemStateChanged(evt);
            }
        });
        jComboBox40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox40ActionPerformed(evt);
            }
        });
        jPanel92.add(jComboBox40);

        jLabel170.setFont(jLabel170.getFont());
        jLabel170.setText(bundle.getString("CrInstrument.jLabel170.text")); 
        jPanel92.add(jLabel170);

        jComboBox50.setEditable(true);
        jComboBox50.setFont(jComboBox50.getFont());
        jComboBox50.setPreferredSize(new java.awt.Dimension(129, 25));
        jComboBox50.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox50ItemStateChanged(evt);
            }
        });
        jPanel92.add(jComboBox50);

        jLabel171.setFont(jLabel171.getFont());
        jLabel171.setText(bundle.getString("CrInstrument.jLabel171.text")); 
        jPanel92.add(jLabel171);

        jComboBox51.setEditable(true);
        jComboBox51.setFont(jComboBox51.getFont());
        jComboBox51.setPreferredSize(new java.awt.Dimension(129, 25));
        jComboBox51.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox51ItemStateChanged(evt);
            }
        });
        jPanel92.add(jComboBox51);

        add(jPanel92);
        jPanel92.setBounds(90, 70, 910, 40);

        curveList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                curveListMouseClicked(evt);
            }
        });
        curveList.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                curveListKeyReleased(evt);
            }
        });
        jScrollPane10.setViewportView(curveList);

        add(jScrollPane10);
        jScrollPane10.setBounds(14, 50, 60, 190);

        jLabel109.setFont(jLabel109.getFont());
        jLabel109.setText(bundle.getString("CrInstrument.jLabel109.text")); 
        add(jLabel109);
        jLabel109.setBounds(20, 30, 60, 15);

        jPanel95.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jButton38.setFont(jButton38.getFont());
        jButton38.setText(bundle.getString("CrInstrument.jButton38.text")); 
        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });
        jPanel95.add(jButton38);

        jButton39.setFont(jButton39.getFont());
        jButton39.setText(bundle.getString("CrInstrument.jButton39.text")); 
        jButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton39ActionPerformed(evt);
            }
        });
        jPanel95.add(jButton39);

        jButton40.setFont(jButton40.getFont());
        jButton40.setText(bundle.getString("CrInstrument.jButton40.text")); 
        jButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton40ActionPerformed(evt);
            }
        });
        jPanel95.add(jButton40);

        add(jPanel95);
        jPanel95.setBounds(90, 30, 670, 40);

        jPanel102.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel103.setFont(jLabel103.getFont());
        jLabel103.setText(bundle.getString("CrInstrument.jLabel103.text")); 
        jPanel102.add(jLabel103);

        jComboBox33.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Trend" }));
        jPanel102.add(jComboBox33);

        add(jPanel102);
        jPanel102.setBounds(90, 150, 660, 40);

        jButton46.setFont(jButton46.getFont());
        jButton46.setText(bundle.getString("CrInstrument.jButton46.text")); 
        jButton46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton46ActionPerformed(evt);
            }
        });
        add(jButton46);
        jButton46.setBounds(10, 240, 120, 30);

        jButton47.setFont(jButton47.getFont());
        jButton47.setText(bundle.getString("CrInstrument.jButton47.text")); 
        jButton47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton47ActionPerformed(evt);
            }
        });
        add(jButton47);
        jButton47.setBounds(10, 270, 120, 30);

        jPanel105.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel106.setFont(jLabel106.getFont());
        jLabel106.setText(bundle.getString("CrInstrument.jLabel106.text")); 
        jPanel105.add(jLabel106);

        jComboBox34.setEditable(true);
        jComboBox34.setFont(jComboBox34.getFont());
        jPanel105.add(jComboBox34);

        jLabel89.setFont(jLabel89.getFont());
        jLabel89.setText(bundle.getString("CrInstrument.jLabel89.text")); 
        jPanel105.add(jLabel89);

        jLabel91.setBackground(new java.awt.Color(255, 255, 255));
        jLabel91.setFont(jLabel91.getFont());
        jLabel91.setText(bundle.getString("CrInstrument.jLabel91.text")); 
        jLabel91.setOpaque(true);
        jPanel105.add(jLabel91);

        jLabel172.setFont(jLabel172.getFont());
        jLabel172.setText(bundle.getString("CrInstrument.jLabel172.text")); 
        jPanel105.add(jLabel172);

        jComboBox52.setEditable(true);
        jComboBox52.setFont(jComboBox52.getFont());
        jComboBox52.setPreferredSize(new java.awt.Dimension(129, 25));
        jPanel105.add(jComboBox52);

        add(jPanel105);
        jPanel105.setBounds(90, 110, 880, 40);

        jPanel107.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel144.setFont(jLabel144.getFont());
        jLabel144.setText(bundle.getString("CrInstrument.jLabel144.text")); 
        jPanel107.add(jLabel144);

        jLabel145.setFont(jLabel145.getFont());
        jLabel145.setText(bundle.getString("CrInstrument.jLabel145.text")); 
        jPanel107.add(jLabel145);

        jLabel59.setBackground(new java.awt.Color(255, 0, 51));
        jLabel59.setText(bundle.getString("CrInstrument.jLabel59.text")); 
        jLabel59.setOpaque(true);
        jLabel59.setPreferredSize(new java.awt.Dimension(40, 25));
        jLabel59.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel59MouseClicked(evt);
            }
        });
        jPanel107.add(jLabel59);

        add(jPanel107);
        jPanel107.setBounds(90, 190, 810, 40);
    }

    private void jComboBox40ItemStateChanged(java.awt.event.ItemEvent evt) {
        if(evt.getStateChange()==evt.SELECTED){
            if(jComboBox40.getSelectedIndex()>0){
                String sel=(String)jComboBox40.getSelectedItem();
                Iterator it=instrument.sensors.values().iterator();
                jComboBox50.removeAllItems();
                jComboBox50.addItem("");
                for(;it.hasNext();){
                    String info[]=ylib.csvlinetoarray((String)it.next());
                    if(info[0].equalsIgnoreCase(sel)){
                        boolean exists = false;
                        for (int index = 0; index < jComboBox50.getItemCount() && !exists; index++) {
                            if (info[1].equals((String)jComboBox50.getItemAt(index))) {
                                exists = true; break;
                            }
                        }
                        if(!exists) {
                            jComboBox50.addItem(info[1]);
                        }
                    }
                }
                jComboBox50.setSelectedIndex(0);
            }
        }
    }

    private void jComboBox40ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jComboBox50ItemStateChanged(java.awt.event.ItemEvent evt) {
        if(evt.getStateChange()==evt.SELECTED){
            if(jComboBox50.getSelectedIndex()>0){
                String station=(String)jComboBox40.getSelectedItem();
                String sel=(String)jComboBox50.getSelectedItem();
                Iterator it=instrument.sensors.values().iterator();
                jComboBox51.removeAllItems();
                jComboBox51.addItem("");
                for(;it.hasNext();){
                    String info[]=ylib.csvlinetoarray((String)it.next());
                    if(info[0].equalsIgnoreCase(station) && info[1].equalsIgnoreCase(sel)){
                        boolean exists=false;
                        for (int index = 0; index < jComboBox51.getItemCount() && !exists; index++) {
                            if (info[2].equals((String)jComboBox51.getItemAt(index))) {
                                exists = true; break;
                            }
                        }
                        if(!exists) {
                            jComboBox51.addItem(info[2]);
                        }
                    }
                }
                jComboBox51.setSelectedIndex(0);
            }
        }
    }

    private void jComboBox51ItemStateChanged(java.awt.event.ItemEvent evt) {
        if(evt.getStateChange()==evt.SELECTED){
            if(jComboBox51.getSelectedIndex()>0){
                String station=(String)jComboBox40.getSelectedItem();
                String device=(String)jComboBox50.getSelectedItem();
                String sel=(String)jComboBox51.getSelectedItem();
                Iterator it=instrument.sensors.values().iterator();
                jComboBox52.removeAllItems();
                jComboBox52.addItem("");
                for(;it.hasNext();){
                    String info[]=ylib.csvlinetoarray((String)it.next());
                    if(info[0].equalsIgnoreCase(station) && info[1].equalsIgnoreCase(device) && info[2].equalsIgnoreCase(sel)){
                        boolean exists=false;
                        for (int index = 0; index < jComboBox52.getItemCount() && !exists; index++) {
                            if (info[4].equals((String)jComboBox52.getItemAt(index))) {
                                exists = true; break;
                            }
                        }
                        if(!exists) {
                            jComboBox52.addItem(info[4]);
                        }
                    }
                }
                jComboBox52.setSelectedIndex(0);
            }
        }
    }

    private void curveListMouseClicked(java.awt.event.MouseEvent evt) {
        showCurve();
    }
void showCurve(){
    if(curveList.getSelectedIndex()>-1){
     String sel=(String)curveList.getSelectedValue();
     if(instrument.curveTM.get(sel)!=null){
       String data[]=ylib.csvlinetoarray((String)instrument.curveTM.get(sel));

       if(data.length>3) jComboBox34.setSelectedItem(data[3]);
       if(data.length>4) jComboBox40.setSelectedItem(data[4]);
       if(data.length>5) jComboBox51.setSelectedItem(data[5]);
       if(data.length>6) jComboBox52.setSelectedItem(data[6]);
       if(data.length>7) jLabel91.setText(data[7]);
       if(data.length>8) jComboBox33.setSelectedItem(data[8]);
       if(data.length>9) jLabel59.setBackground(new Color(Integer.parseInt(data[9])));
       if(data.length>10) jComboBox50.setSelectedItem(data[10]);
       }
     }
}
    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {
        int cnt=curveList.getModel().getSize();
        int max=0;
        if(cnt>0){
            for(int i=0;i<cnt;i++) {
                String tm=(String)curveList.getModel().getElementAt(i);
                int v=Integer.parseInt(tm.substring(2));
                if(v>max) max=v;
            }
        }
        max=max+1;
        String newItem="CV"+instrument.zero(4-String.valueOf(max).length())+max;
        curveListModel.addElement(newItem);
        curveList.setSelectedValue(newItem, true);
        instrument.curveTM.put(newItem, newItem+",");
    }

    private void jButton39ActionPerformed(java.awt.event.ActionEvent evt) {
        if(curveList.getSelectedIndex()>-1){
            int selNo=curveList.getSelectedIndex();
            String sel=(String)curveList.getSelectedValue();
            curveListModel.removeElement(sel);
            instrument.curveTM.remove(sel);
            if(curveListModel.size() < selNo+1) selNo=curveListModel.size()-1;
            if(selNo>-1){
                curveList.setSelectedIndex(selNo);
                sel=(String)curveList.getSelectedValue();
                showCurve();
            }
        }
    }

    private void jButton40ActionPerformed(java.awt.event.ActionEvent evt) {
        if(curveList.getSelectedIndex()>-1){
            String sel=(String)curveList.getSelectedValue();
            String data[]=new String[instrument.curveMaxArrCnt];
            for(int i=0;i<data.length;i++) data[i]="";
          if(instrument.curveTM.get(sel)!=null){
            String data2[]=ylib.csvlinetoarray((String)instrument.curveTM.get(sel));
            for(int i=0;i<data2.length && i<data.length;i++) data[i]=data2[i];
          }
        data[0]=sel;
        data[1]="";
        data[2]="";
        data[3]=(String)jComboBox34.getSelectedItem();
        data[4]=(String)jComboBox40.getSelectedItem();
        data[5]=(String)jComboBox51.getSelectedItem();
        data[6]=(String)jComboBox52.getSelectedItem();
        data[7]=jLabel91.getText();
        data[8]=(String)jComboBox33.getSelectedItem();

        data[9]=String.valueOf(jLabel59.getBackground().getRGB());
        data[10]=(String)jComboBox50.getSelectedItem();
        instrument.curveTM.put(sel, data);
        }
    }

    private void jButton46ActionPerformed(java.awt.event.ActionEvent evt) {
        int sel=curveList.getSelectedIndex();
        if(sel>0){
            String key=(String)curveList.getSelectedValue();
            String data=(String)instrument.curveTM.get(key);
            curveList.setSelectedIndex(sel-1);
            String key2=(String)curveList.getSelectedValue();
            String data2=(String)instrument.curveTM.get(key2);
            instrument.curveTM.put(key, data2);
            instrument.curveTM.put(key2, data);
        }
    }

    private void jButton47ActionPerformed(java.awt.event.ActionEvent evt) {
        int sel=curveList.getSelectedIndex();
        if(sel>-1 && sel<(curveListModel.size()-1)){
            String key=(String)curveList.getSelectedValue();
            String data=(String)instrument.curveTM.get(key);
            curveList.setSelectedIndex(sel+1);
            String key2=(String)curveList.getSelectedValue();
            String data2=(String)instrument.curveTM.get(key2);
            instrument.curveTM.put(key, data2);
            instrument.curveTM.put(key2, data);
        }
    }

    private void jLabel59MouseClicked(java.awt.event.MouseEvent evt) {
        Color newColor = JColorChooser.showDialog(null, "Choose a color", jLabel59.getBackground());
        if(newColor!=null) jLabel59.setBackground(newColor);
    }

    private void curveListKeyReleased(java.awt.event.KeyEvent evt) {
      if(evt.getKeyCode()==38 || evt.getKeyCode()==40 ) showCurve();
    }

    javax.swing.JList curveList;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    javax.swing.JComboBox jComboBox33;
    javax.swing.JComboBox jComboBox34;
    javax.swing.JComboBox jComboBox40;
    javax.swing.JComboBox jComboBox50;
    javax.swing.JComboBox jComboBox51;
    javax.swing.JComboBox jComboBox52;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel144;
    private javax.swing.JLabel jLabel145;
    private javax.swing.JLabel jLabel169;
    private javax.swing.JLabel jLabel170;
    private javax.swing.JLabel jLabel171;
    private javax.swing.JLabel jLabel172;
    javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JPanel jPanel102;
    private javax.swing.JPanel jPanel105;
    private javax.swing.JPanel jPanel107;
    private javax.swing.JPanel jPanel92;
    private javax.swing.JPanel jPanel95;
    private javax.swing.JScrollPane jScrollPane10;

}