
package ci;

/**
 *
 * @author peter
 */
public class CIDataPanel extends javax.swing.JPanel {

  CrInstrument instrument;
    public CIDataPanel(CrInstrument instrument) {
        this.instrument=instrument;
        initComponents();
        da_device_01.setText("");
        da_dataname_01.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void initComponents() {

        da_datavalue_01 = new javax.swing.JLabel();
        da_device_01 = new javax.swing.JLabel();
        da_dataname_01 = new javax.swing.JLabel();
        da_station_01 = new javax.swing.JLabel();
        da_station_02 = new javax.swing.JLabel();
        da_station_03 = new javax.swing.JLabel();
        da_station_04 = new javax.swing.JLabel();
        da_station_05 = new javax.swing.JLabel();
        da_station_06 = new javax.swing.JLabel();
        da_station_07 = new javax.swing.JLabel();
        da_station_08 = new javax.swing.JLabel();
        da_station_09 = new javax.swing.JLabel();
        da_station_10 = new javax.swing.JLabel();
        da_station_11 = new javax.swing.JLabel();
        da_station_12 = new javax.swing.JLabel();
        da_station_13 = new javax.swing.JLabel();
        da_station_14 = new javax.swing.JLabel();
        da_station_15 = new javax.swing.JLabel();
        da_station_16 = new javax.swing.JLabel();
        da_device_02 = new javax.swing.JLabel();
        da_device_03 = new javax.swing.JLabel();
        da_device_04 = new javax.swing.JLabel();
        da_device_05 = new javax.swing.JLabel();
        da_device_06 = new javax.swing.JLabel();
        da_device_07 = new javax.swing.JLabel();
        da_device_08 = new javax.swing.JLabel();
        da_device_09 = new javax.swing.JLabel();
        da_device_10 = new javax.swing.JLabel();
        da_device_11 = new javax.swing.JLabel();
        da_device_12 = new javax.swing.JLabel();
        da_device_13 = new javax.swing.JLabel();
        da_device_14 = new javax.swing.JLabel();
        da_device_15 = new javax.swing.JLabel();
        da_device_16 = new javax.swing.JLabel();
        da_device_17 = new javax.swing.JLabel();
        da_device_18 = new javax.swing.JLabel();
        da_device_19 = new javax.swing.JLabel();
        da_device_20 = new javax.swing.JLabel();
        da_device_21 = new javax.swing.JLabel();
        da_device_22 = new javax.swing.JLabel();
        da_device_23 = new javax.swing.JLabel();
        da_device_24 = new javax.swing.JLabel();
        da_device_25 = new javax.swing.JLabel();
        da_device_26 = new javax.swing.JLabel();
        da_device_27 = new javax.swing.JLabel();
        da_device_28 = new javax.swing.JLabel();
        da_device_29 = new javax.swing.JLabel();
        da_device_30 = new javax.swing.JLabel();
        da_device_31 = new javax.swing.JLabel();
        da_device_32 = new javax.swing.JLabel();
        da_dataname_02 = new javax.swing.JLabel();
        da_dataname_03 = new javax.swing.JLabel();
        da_dataname_04 = new javax.swing.JLabel();
        da_dataname_05 = new javax.swing.JLabel();
        da_dataname_06 = new javax.swing.JLabel();
        da_dataname_07 = new javax.swing.JLabel();
        da_dataname_08 = new javax.swing.JLabel();
        da_dataname_09 = new javax.swing.JLabel();
        da_dataname_10 = new javax.swing.JLabel();
        da_dataname_11 = new javax.swing.JLabel();
        da_dataname_12 = new javax.swing.JLabel();
        da_dataname_13 = new javax.swing.JLabel();
        da_dataname_14 = new javax.swing.JLabel();
        da_dataname_15 = new javax.swing.JLabel();
        da_dataname_16 = new javax.swing.JLabel();
        da_dataname_17 = new javax.swing.JLabel();
        da_dataname_18 = new javax.swing.JLabel();
        da_dataname_19 = new javax.swing.JLabel();
        da_dataname_20 = new javax.swing.JLabel();
        da_dataname_21 = new javax.swing.JLabel();
        da_dataname_22 = new javax.swing.JLabel();
        da_dataname_23 = new javax.swing.JLabel();
        da_dataname_24 = new javax.swing.JLabel();
        da_dataname_25 = new javax.swing.JLabel();
        da_dataname_26 = new javax.swing.JLabel();
        da_dataname_27 = new javax.swing.JLabel();
        da_dataname_28 = new javax.swing.JLabel();
        da_dataname_29 = new javax.swing.JLabel();
        da_dataname_30 = new javax.swing.JLabel();
        da_dataname_31 = new javax.swing.JLabel();
        da_dataname_32 = new javax.swing.JLabel();
        da_dataname_33 = new javax.swing.JLabel();
        da_dataname_34 = new javax.swing.JLabel();
        da_dataname_35 = new javax.swing.JLabel();
        da_dataname_36 = new javax.swing.JLabel();
        da_dataname_37 = new javax.swing.JLabel();
        da_dataname_38 = new javax.swing.JLabel();
        da_dataname_39 = new javax.swing.JLabel();
        da_dataname_40 = new javax.swing.JLabel();
        da_dataname_41 = new javax.swing.JLabel();
        da_dataname_42 = new javax.swing.JLabel();
        da_dataname_43 = new javax.swing.JLabel();
        da_dataname_44 = new javax.swing.JLabel();
        da_dataname_45 = new javax.swing.JLabel();
        da_dataname_46 = new javax.swing.JLabel();
        da_dataname_47 = new javax.swing.JLabel();
        da_dataname_48 = new javax.swing.JLabel();
        da_datavalue_02 = new javax.swing.JLabel();
        da_datavalue_03 = new javax.swing.JLabel();
        da_datavalue_04 = new javax.swing.JLabel();
        da_datavalue_05 = new javax.swing.JLabel();
        da_datavalue_06 = new javax.swing.JLabel();
        da_datavalue_07 = new javax.swing.JLabel();
        da_datavalue_08 = new javax.swing.JLabel();
        da_datavalue_09 = new javax.swing.JLabel();
        da_datavalue_10 = new javax.swing.JLabel();
        da_datavalue_11 = new javax.swing.JLabel();
        da_datavalue_12 = new javax.swing.JLabel();
        da_datavalue_13 = new javax.swing.JLabel();
        da_datavalue_14 = new javax.swing.JLabel();
        da_datavalue_15 = new javax.swing.JLabel();
        da_datavalue_16 = new javax.swing.JLabel();
        da_datavalue_17 = new javax.swing.JLabel();
        da_datavalue_18 = new javax.swing.JLabel();
        da_datavalue_19 = new javax.swing.JLabel();
        da_datavalue_20 = new javax.swing.JLabel();
        da_datavalue_21 = new javax.swing.JLabel();
        da_datavalue_22 = new javax.swing.JLabel();
        da_datavalue_23 = new javax.swing.JLabel();
        da_datavalue_24 = new javax.swing.JLabel();
        da_datavalue_25 = new javax.swing.JLabel();
        da_datavalue_26 = new javax.swing.JLabel();
        da_datavalue_27 = new javax.swing.JLabel();
        da_datavalue_28 = new javax.swing.JLabel();
        da_datavalue_29 = new javax.swing.JLabel();
        da_datavalue_30 = new javax.swing.JLabel();
        da_datavalue_31 = new javax.swing.JLabel();
        da_datavalue_32 = new javax.swing.JLabel();
        da_datavalue_33 = new javax.swing.JLabel();
        da_datavalue_34 = new javax.swing.JLabel();
        da_datavalue_35 = new javax.swing.JLabel();
        da_datavalue_36 = new javax.swing.JLabel();
        da_datavalue_37 = new javax.swing.JLabel();
        da_datavalue_38 = new javax.swing.JLabel();
        da_datavalue_39 = new javax.swing.JLabel();
        da_datavalue_40 = new javax.swing.JLabel();
        da_datavalue_41 = new javax.swing.JLabel();
        da_datavalue_42 = new javax.swing.JLabel();
        da_datavalue_43 = new javax.swing.JLabel();
        da_datavalue_44 = new javax.swing.JLabel();
        da_datavalue_45 = new javax.swing.JLabel();
        da_datavalue_46 = new javax.swing.JLabel();
        da_datavalue_47 = new javax.swing.JLabel();
        da_datavalue_48 = new javax.swing.JLabel();
        da_xlabel_01 = new javax.swing.JLabel();
        da_xlabel_02 = new javax.swing.JLabel();
        da_xlabel_03 = new javax.swing.JLabel();
        da_xlabel_04 = new javax.swing.JLabel();
        da_xlabel_05 = new javax.swing.JLabel();
        da_xlabel_06 = new javax.swing.JLabel();
        da_xlabel_07 = new javax.swing.JLabel();
        da_xlabel_08 = new javax.swing.JLabel();
        da_xlabel_09 = new javax.swing.JLabel();
        da_xlabel_10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("ci/Bundle"); 
        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), bundle.getString("DataPanel.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("·s²Ó©úÅé", 0, 12), new java.awt.Color(255, 255, 255))); 
        setLayout(null);

        da_datavalue_01.setFont(da_datavalue_01.getFont().deriveFont(da_datavalue_01.getFont().getStyle() | java.awt.Font.BOLD, da_datavalue_01.getFont().getSize()+36));
        da_datavalue_01.setForeground(new java.awt.Color(255, 0, 51));
        da_datavalue_01.setText("1000.09");
        add(da_datavalue_01);
        da_datavalue_01.setBounds(60, 150, 300, 60);

        da_device_01.setFont(da_device_01.getFont().deriveFont(da_device_01.getFont().getStyle() | java.awt.Font.BOLD, da_device_01.getFont().getSize()+6));
        da_device_01.setForeground(new java.awt.Color(0, 255, 102));
        da_device_01.setText("device 01");
        add(da_device_01);
        da_device_01.setBounds(20, 60, 320, 30);

        da_dataname_01.setFont(da_dataname_01.getFont().deriveFont(da_dataname_01.getFont().getStyle() | java.awt.Font.BOLD, da_dataname_01.getFont().getSize()+6));
        da_dataname_01.setForeground(new java.awt.Color(255, 255, 51));
        da_dataname_01.setText("Temperature");
        add(da_dataname_01);
        da_dataname_01.setBounds(20, 110, 320, 30);

        da_station_01.setFont(da_station_01.getFont().deriveFont(da_station_01.getFont().getStyle() | java.awt.Font.BOLD, da_station_01.getFont().getSize()+6));
        da_station_01.setForeground(new java.awt.Color(153, 255, 255));
        da_station_01.setText("Station 01");
        add(da_station_01);
        da_station_01.setBounds(20, 30, 280, 20);

        da_station_02.setFont(da_station_02.getFont().deriveFont(da_station_02.getFont().getStyle() | java.awt.Font.BOLD, da_station_02.getFont().getSize()+6));
        da_station_02.setForeground(new java.awt.Color(153, 255, 255));
        da_station_02.setText("Station 02");
        add(da_station_02);
        da_station_02.setBounds(20, 30, 280, 20);

        da_station_03.setFont(da_station_03.getFont().deriveFont(da_station_03.getFont().getStyle() | java.awt.Font.BOLD, da_station_03.getFont().getSize()+6));
        da_station_03.setForeground(new java.awt.Color(153, 255, 255));
        da_station_03.setText("Station 03");
        add(da_station_03);
        da_station_03.setBounds(20, 30, 280, 20);

        da_station_04.setFont(da_station_04.getFont().deriveFont(da_station_04.getFont().getStyle() | java.awt.Font.BOLD, da_station_04.getFont().getSize()+6));
        da_station_04.setForeground(new java.awt.Color(153, 255, 255));
        da_station_04.setText("Station 04");
        add(da_station_04);
        da_station_04.setBounds(20, 30, 280, 20);

        da_station_05.setFont(da_station_05.getFont().deriveFont(da_station_05.getFont().getStyle() | java.awt.Font.BOLD, da_station_05.getFont().getSize()+6));
        da_station_05.setForeground(new java.awt.Color(153, 255, 255));
        da_station_05.setText("Station 05");
        add(da_station_05);
        da_station_05.setBounds(20, 30, 280, 20);

        da_station_06.setFont(da_station_06.getFont().deriveFont(da_station_06.getFont().getStyle() | java.awt.Font.BOLD, da_station_06.getFont().getSize()+6));
        da_station_06.setForeground(new java.awt.Color(153, 255, 255));
        da_station_06.setText("Station 06");
        add(da_station_06);
        da_station_06.setBounds(20, 30, 280, 20);

        da_station_07.setFont(da_station_07.getFont().deriveFont(da_station_07.getFont().getStyle() | java.awt.Font.BOLD, da_station_07.getFont().getSize()+6));
        da_station_07.setForeground(new java.awt.Color(153, 255, 255));
        da_station_07.setText("Station 07");
        add(da_station_07);
        da_station_07.setBounds(20, 30, 280, 20);

        da_station_08.setFont(da_station_08.getFont().deriveFont(da_station_08.getFont().getStyle() | java.awt.Font.BOLD, da_station_08.getFont().getSize()+6));
        da_station_08.setForeground(new java.awt.Color(153, 255, 255));
        da_station_08.setText("Station 08");
        add(da_station_08);
        da_station_08.setBounds(20, 30, 280, 20);

        da_station_09.setFont(da_station_09.getFont().deriveFont(da_station_09.getFont().getStyle() | java.awt.Font.BOLD, da_station_09.getFont().getSize()+6));
        da_station_09.setForeground(new java.awt.Color(153, 255, 255));
        da_station_09.setText("Station 09");
        add(da_station_09);
        da_station_09.setBounds(20, 30, 280, 20);

        da_station_10.setFont(da_station_10.getFont().deriveFont(da_station_10.getFont().getStyle() | java.awt.Font.BOLD, da_station_10.getFont().getSize()+6));
        da_station_10.setForeground(new java.awt.Color(153, 255, 255));
        da_station_10.setText("Station 10");
        add(da_station_10);
        da_station_10.setBounds(20, 30, 280, 20);

        da_station_11.setFont(da_station_11.getFont().deriveFont(da_station_11.getFont().getStyle() | java.awt.Font.BOLD, da_station_11.getFont().getSize()+6));
        da_station_11.setForeground(new java.awt.Color(153, 255, 255));
        da_station_11.setText("Station 11");
        add(da_station_11);
        da_station_11.setBounds(20, 30, 280, 20);

        da_station_12.setFont(da_station_12.getFont().deriveFont(da_station_12.getFont().getStyle() | java.awt.Font.BOLD, da_station_12.getFont().getSize()+6));
        da_station_12.setForeground(new java.awt.Color(153, 255, 255));
        da_station_12.setText("Station 12");
        add(da_station_12);
        da_station_12.setBounds(20, 30, 280, 20);

        da_station_13.setFont(da_station_13.getFont().deriveFont(da_station_13.getFont().getStyle() | java.awt.Font.BOLD, da_station_13.getFont().getSize()+6));
        da_station_13.setForeground(new java.awt.Color(153, 255, 255));
        da_station_13.setText("Station 13");
        add(da_station_13);
        da_station_13.setBounds(20, 30, 280, 20);

        da_station_14.setFont(da_station_14.getFont().deriveFont(da_station_14.getFont().getStyle() | java.awt.Font.BOLD, da_station_14.getFont().getSize()+6));
        da_station_14.setForeground(new java.awt.Color(153, 255, 255));
        da_station_14.setText("Station 14");
        add(da_station_14);
        da_station_14.setBounds(20, 30, 280, 20);

        da_station_15.setFont(da_station_15.getFont().deriveFont(da_station_15.getFont().getStyle() | java.awt.Font.BOLD, da_station_15.getFont().getSize()+6));
        da_station_15.setForeground(new java.awt.Color(153, 255, 255));
        da_station_15.setText("Station 15");
        add(da_station_15);
        da_station_15.setBounds(20, 30, 280, 20);

        da_station_16.setFont(da_station_16.getFont().deriveFont(da_station_16.getFont().getStyle() | java.awt.Font.BOLD, da_station_16.getFont().getSize()+6));
        da_station_16.setForeground(new java.awt.Color(153, 255, 255));
        da_station_16.setText("Station 16");
        add(da_station_16);
        da_station_16.setBounds(20, 30, 280, 20);

        da_device_02.setFont(da_device_02.getFont().deriveFont(da_device_02.getFont().getStyle() | java.awt.Font.BOLD, da_device_02.getFont().getSize()+6));
        da_device_02.setForeground(new java.awt.Color(0, 255, 102));
        da_device_02.setText("device 02");
        add(da_device_02);
        da_device_02.setBounds(20, 60, 320, 30);

        da_device_03.setFont(da_device_03.getFont().deriveFont(da_device_03.getFont().getStyle() | java.awt.Font.BOLD, da_device_03.getFont().getSize()+6));
        da_device_03.setForeground(new java.awt.Color(0, 255, 102));
        da_device_03.setText("device 03");
        add(da_device_03);
        da_device_03.setBounds(20, 60, 320, 30);

        da_device_04.setFont(da_device_04.getFont().deriveFont(da_device_04.getFont().getStyle() | java.awt.Font.BOLD, da_device_04.getFont().getSize()+6));
        da_device_04.setForeground(new java.awt.Color(0, 255, 102));
        da_device_04.setText("device 03");
        add(da_device_04);
        da_device_04.setBounds(20, 60, 320, 30);

        da_device_05.setFont(da_device_05.getFont().deriveFont(da_device_05.getFont().getStyle() | java.awt.Font.BOLD, da_device_05.getFont().getSize()+6));
        da_device_05.setForeground(new java.awt.Color(0, 255, 102));
        da_device_05.setText("device 05");
        add(da_device_05);
        da_device_05.setBounds(20, 60, 320, 30);

        da_device_06.setFont(da_device_06.getFont().deriveFont(da_device_06.getFont().getStyle() | java.awt.Font.BOLD, da_device_06.getFont().getSize()+6));
        da_device_06.setForeground(new java.awt.Color(0, 255, 102));
        da_device_06.setText("device 06");
        add(da_device_06);
        da_device_06.setBounds(20, 60, 320, 30);

        da_device_07.setFont(da_device_07.getFont().deriveFont(da_device_07.getFont().getStyle() | java.awt.Font.BOLD, da_device_07.getFont().getSize()+6));
        da_device_07.setForeground(new java.awt.Color(0, 255, 102));
        da_device_07.setText("device 07");
        add(da_device_07);
        da_device_07.setBounds(20, 60, 320, 30);

        da_device_08.setFont(da_device_08.getFont().deriveFont(da_device_08.getFont().getStyle() | java.awt.Font.BOLD, da_device_08.getFont().getSize()+6));
        da_device_08.setForeground(new java.awt.Color(0, 255, 102));
        da_device_08.setText("device 08");
        add(da_device_08);
        da_device_08.setBounds(20, 60, 320, 30);

        da_device_09.setFont(da_device_09.getFont().deriveFont(da_device_09.getFont().getStyle() | java.awt.Font.BOLD, da_device_09.getFont().getSize()+6));
        da_device_09.setForeground(new java.awt.Color(0, 255, 102));
        da_device_09.setText("device 09");
        add(da_device_09);
        da_device_09.setBounds(20, 60, 320, 30);

        da_device_10.setFont(da_device_10.getFont().deriveFont(da_device_10.getFont().getStyle() | java.awt.Font.BOLD, da_device_10.getFont().getSize()+6));
        da_device_10.setForeground(new java.awt.Color(0, 255, 102));
        da_device_10.setText("device 10");
        add(da_device_10);
        da_device_10.setBounds(20, 60, 320, 30);

        da_device_11.setFont(da_device_11.getFont().deriveFont(da_device_11.getFont().getStyle() | java.awt.Font.BOLD, da_device_11.getFont().getSize()+6));
        da_device_11.setForeground(new java.awt.Color(0, 255, 102));
        da_device_11.setText("device 11");
        add(da_device_11);
        da_device_11.setBounds(20, 60, 320, 30);

        da_device_12.setFont(da_device_12.getFont().deriveFont(da_device_12.getFont().getStyle() | java.awt.Font.BOLD, da_device_12.getFont().getSize()+6));
        da_device_12.setForeground(new java.awt.Color(0, 255, 102));
        da_device_12.setText("device 12");
        add(da_device_12);
        da_device_12.setBounds(20, 60, 320, 30);

        da_device_13.setFont(da_device_13.getFont().deriveFont(da_device_13.getFont().getStyle() | java.awt.Font.BOLD, da_device_13.getFont().getSize()+6));
        da_device_13.setForeground(new java.awt.Color(0, 255, 102));
        da_device_13.setText("device 13");
        add(da_device_13);
        da_device_13.setBounds(20, 60, 320, 30);

        da_device_14.setFont(da_device_14.getFont().deriveFont(da_device_14.getFont().getStyle() | java.awt.Font.BOLD, da_device_14.getFont().getSize()+6));
        da_device_14.setForeground(new java.awt.Color(0, 255, 102));
        da_device_14.setText("device 14");
        add(da_device_14);
        da_device_14.setBounds(20, 60, 320, 30);

        da_device_15.setFont(da_device_15.getFont().deriveFont(da_device_15.getFont().getStyle() | java.awt.Font.BOLD, da_device_15.getFont().getSize()+6));
        da_device_15.setForeground(new java.awt.Color(0, 255, 102));
        da_device_15.setText("device 15");
        add(da_device_15);
        da_device_15.setBounds(20, 60, 320, 30);

        da_device_16.setFont(da_device_16.getFont().deriveFont(da_device_16.getFont().getStyle() | java.awt.Font.BOLD, da_device_16.getFont().getSize()+6));
        da_device_16.setForeground(new java.awt.Color(0, 255, 102));
        da_device_16.setText("device 16");
        add(da_device_16);
        da_device_16.setBounds(20, 60, 320, 30);

        da_device_17.setFont(da_device_17.getFont().deriveFont(da_device_17.getFont().getStyle() | java.awt.Font.BOLD, da_device_17.getFont().getSize()+6));
        da_device_17.setForeground(new java.awt.Color(0, 255, 102));
        da_device_17.setText("device 17");
        add(da_device_17);
        da_device_17.setBounds(20, 60, 320, 30);

        da_device_18.setFont(da_device_18.getFont().deriveFont(da_device_18.getFont().getStyle() | java.awt.Font.BOLD, da_device_18.getFont().getSize()+6));
        da_device_18.setForeground(new java.awt.Color(0, 255, 102));
        da_device_18.setText("device 18");
        add(da_device_18);
        da_device_18.setBounds(20, 60, 320, 30);

        da_device_19.setFont(da_device_19.getFont().deriveFont(da_device_19.getFont().getStyle() | java.awt.Font.BOLD, da_device_19.getFont().getSize()+6));
        da_device_19.setForeground(new java.awt.Color(0, 255, 102));
        da_device_19.setText("device 19");
        add(da_device_19);
        da_device_19.setBounds(20, 60, 320, 30);

        da_device_20.setFont(da_device_20.getFont().deriveFont(da_device_20.getFont().getStyle() | java.awt.Font.BOLD, da_device_20.getFont().getSize()+6));
        da_device_20.setForeground(new java.awt.Color(0, 255, 102));
        da_device_20.setText("device 20");
        add(da_device_20);
        da_device_20.setBounds(20, 60, 320, 30);

        da_device_21.setFont(da_device_21.getFont().deriveFont(da_device_21.getFont().getStyle() | java.awt.Font.BOLD, da_device_21.getFont().getSize()+6));
        da_device_21.setForeground(new java.awt.Color(0, 255, 102));
        da_device_21.setText("device 21");
        add(da_device_21);
        da_device_21.setBounds(20, 60, 320, 30);

        da_device_22.setFont(da_device_22.getFont().deriveFont(da_device_22.getFont().getStyle() | java.awt.Font.BOLD, da_device_22.getFont().getSize()+6));
        da_device_22.setForeground(new java.awt.Color(0, 255, 102));
        da_device_22.setText("device 22");
        add(da_device_22);
        da_device_22.setBounds(20, 60, 320, 30);

        da_device_23.setFont(da_device_23.getFont().deriveFont(da_device_23.getFont().getStyle() | java.awt.Font.BOLD, da_device_23.getFont().getSize()+6));
        da_device_23.setForeground(new java.awt.Color(0, 255, 102));
        da_device_23.setText("device 23");
        add(da_device_23);
        da_device_23.setBounds(20, 60, 320, 30);

        da_device_24.setFont(da_device_24.getFont().deriveFont(da_device_24.getFont().getStyle() | java.awt.Font.BOLD, da_device_24.getFont().getSize()+6));
        da_device_24.setForeground(new java.awt.Color(0, 255, 102));
        da_device_24.setText("device 24");
        add(da_device_24);
        da_device_24.setBounds(20, 60, 320, 30);

        da_device_25.setFont(da_device_25.getFont().deriveFont(da_device_25.getFont().getStyle() | java.awt.Font.BOLD, da_device_25.getFont().getSize()+6));
        da_device_25.setForeground(new java.awt.Color(0, 255, 102));
        da_device_25.setText("device 25");
        add(da_device_25);
        da_device_25.setBounds(20, 60, 320, 30);

        da_device_26.setFont(da_device_26.getFont().deriveFont(da_device_26.getFont().getStyle() | java.awt.Font.BOLD, da_device_26.getFont().getSize()+6));
        da_device_26.setForeground(new java.awt.Color(0, 255, 102));
        da_device_26.setText("device 26");
        add(da_device_26);
        da_device_26.setBounds(20, 60, 320, 30);

        da_device_27.setFont(da_device_27.getFont().deriveFont(da_device_27.getFont().getStyle() | java.awt.Font.BOLD, da_device_27.getFont().getSize()+6));
        da_device_27.setForeground(new java.awt.Color(0, 255, 102));
        da_device_27.setText("device 27");
        add(da_device_27);
        da_device_27.setBounds(20, 60, 320, 30);

        da_device_28.setFont(da_device_28.getFont().deriveFont(da_device_28.getFont().getStyle() | java.awt.Font.BOLD, da_device_28.getFont().getSize()+6));
        da_device_28.setForeground(new java.awt.Color(0, 255, 102));
        da_device_28.setText("device 28");
        add(da_device_28);
        da_device_28.setBounds(20, 60, 320, 30);

        da_device_29.setFont(da_device_29.getFont().deriveFont(da_device_29.getFont().getStyle() | java.awt.Font.BOLD, da_device_29.getFont().getSize()+6));
        da_device_29.setForeground(new java.awt.Color(0, 255, 102));
        da_device_29.setText("device 29");
        add(da_device_29);
        da_device_29.setBounds(20, 60, 320, 30);

        da_device_30.setFont(da_device_30.getFont().deriveFont(da_device_30.getFont().getStyle() | java.awt.Font.BOLD, da_device_30.getFont().getSize()+6));
        da_device_30.setForeground(new java.awt.Color(0, 255, 102));
        da_device_30.setText("device 30");
        add(da_device_30);
        da_device_30.setBounds(20, 60, 320, 30);

        da_device_31.setFont(da_device_31.getFont().deriveFont(da_device_31.getFont().getStyle() | java.awt.Font.BOLD, da_device_31.getFont().getSize()+6));
        da_device_31.setForeground(new java.awt.Color(0, 255, 102));
        da_device_31.setText("device 31");
        add(da_device_31);
        da_device_31.setBounds(20, 60, 320, 30);

        da_device_32.setFont(da_device_32.getFont().deriveFont(da_device_32.getFont().getStyle() | java.awt.Font.BOLD, da_device_32.getFont().getSize()+6));
        da_device_32.setForeground(new java.awt.Color(0, 255, 102));
        da_device_32.setText("device 32");
        add(da_device_32);
        da_device_32.setBounds(20, 60, 320, 30);

        da_dataname_02.setFont(da_dataname_02.getFont().deriveFont(da_dataname_02.getFont().getStyle() | java.awt.Font.BOLD, da_dataname_02.getFont().getSize()+6));
        da_dataname_02.setForeground(new java.awt.Color(255, 255, 51));
        da_dataname_02.setText("Temperature");
        add(da_dataname_02);
        da_dataname_02.setBounds(20, 110, 320, 30);

        da_dataname_03.setFont(da_dataname_03.getFont().deriveFont(da_dataname_03.getFont().getStyle() | java.awt.Font.BOLD, da_dataname_03.getFont().getSize()+6));
        da_dataname_03.setForeground(new java.awt.Color(255, 255, 51));
        da_dataname_03.setText("Temperature");
        add(da_dataname_03);
        da_dataname_03.setBounds(20, 110, 320, 30);

        da_dataname_04.setFont(da_dataname_04.getFont().deriveFont(da_dataname_04.getFont().getStyle() | java.awt.Font.BOLD, da_dataname_04.getFont().getSize()+6));
        da_dataname_04.setForeground(new java.awt.Color(255, 255, 51));
        da_dataname_04.setText("Temperature");
        add(da_dataname_04);
        da_dataname_04.setBounds(20, 110, 320, 30);

        da_dataname_05.setFont(da_dataname_05.getFont().deriveFont(da_dataname_05.getFont().getStyle() | java.awt.Font.BOLD, da_dataname_05.getFont().getSize()+6));
        da_dataname_05.setForeground(new java.awt.Color(255, 255, 51));
        da_dataname_05.setText("Temperature");
        add(da_dataname_05);
        da_dataname_05.setBounds(20, 110, 320, 30);

        da_dataname_06.setFont(da_dataname_06.getFont().deriveFont(da_dataname_06.getFont().getStyle() | java.awt.Font.BOLD, da_dataname_06.getFont().getSize()+6));
        da_dataname_06.setForeground(new java.awt.Color(255, 255, 51));
        da_dataname_06.setText("Temperature");
        add(da_dataname_06);
        da_dataname_06.setBounds(20, 110, 320, 30);

        da_dataname_07.setFont(da_dataname_07.getFont().deriveFont(da_dataname_07.getFont().getStyle() | java.awt.Font.BOLD, da_dataname_07.getFont().getSize()+6));
        da_dataname_07.setForeground(new java.awt.Color(255, 255, 51));
        da_dataname_07.setText("Temperature");
        add(da_dataname_07);
        da_dataname_07.setBounds(20, 110, 320, 30);

        da_dataname_08.setFont(da_dataname_08.getFont().deriveFont(da_dataname_08.getFont().getStyle() | java.awt.Font.BOLD, da_dataname_08.getFont().getSize()+6));
        da_dataname_08.setForeground(new java.awt.Color(255, 255, 51));
        da_dataname_08.setText("Temperature");
        add(da_dataname_08);
        da_dataname_08.setBounds(20, 110, 320, 30);

        da_dataname_09.setFont(da_dataname_09.getFont().deriveFont(da_dataname_09.getFont().getStyle() | java.awt.Font.BOLD, da_dataname_09.getFont().getSize()+6));
        da_dataname_09.setForeground(new java.awt.Color(255, 255, 51));
        da_dataname_09.setText("Temperature");
        add(da_dataname_09);
        da_dataname_09.setBounds(20, 110, 320, 30);

        da_dataname_10.setFont(da_dataname_10.getFont().deriveFont(da_dataname_10.getFont().getStyle() | java.awt.Font.BOLD, da_dataname_10.getFont().getSize()+6));
        da_dataname_10.setForeground(new java.awt.Color(255, 255, 51));
        da_dataname_10.setText("Temperature");
        add(da_dataname_10);
        da_dataname_10.setBounds(20, 110, 320, 30);

        da_dataname_11.setFont(da_dataname_11.getFont().deriveFont(da_dataname_11.getFont().getStyle() | java.awt.Font.BOLD, da_dataname_11.getFont().getSize()+6));
        da_dataname_11.setForeground(new java.awt.Color(255, 255, 51));
        da_dataname_11.setText("Temperature");
        add(da_dataname_11);
        da_dataname_11.setBounds(20, 110, 320, 30);

        da_dataname_12.setFont(da_dataname_12.getFont().deriveFont(da_dataname_12.getFont().getStyle() | java.awt.Font.BOLD, da_dataname_12.getFont().getSize()+6));
        da_dataname_12.setForeground(new java.awt.Color(255, 255, 51));
        da_dataname_12.setText("Temperature");
        add(da_dataname_12);
        da_dataname_12.setBounds(20, 110, 320, 30);

        da_dataname_13.setFont(da_dataname_13.getFont().deriveFont(da_dataname_13.getFont().getStyle() | java.awt.Font.BOLD, da_dataname_13.getFont().getSize()+6));
        da_dataname_13.setForeground(new java.awt.Color(255, 255, 51));
        da_dataname_13.setText("Temperature");
        add(da_dataname_13);
        da_dataname_13.setBounds(20, 110, 320, 30);

        da_dataname_14.setFont(da_dataname_14.getFont().deriveFont(da_dataname_14.getFont().getStyle() | java.awt.Font.BOLD, da_dataname_14.getFont().getSize()+6));
        da_dataname_14.setForeground(new java.awt.Color(255, 255, 51));
        da_dataname_14.setText("Temperature");
        add(da_dataname_14);
        da_dataname_14.setBounds(20, 110, 320, 30);

        da_dataname_15.setFont(da_dataname_15.getFont().deriveFont(da_dataname_15.getFont().getStyle() | java.awt.Font.BOLD, da_dataname_15.getFont().getSize()+6));
        da_dataname_15.setForeground(new java.awt.Color(255, 255, 51));
        da_dataname_15.setText("Temperature");
        add(da_dataname_15);
        da_dataname_15.setBounds(20, 110, 320, 30);

        da_dataname_16.setFont(da_dataname_16.getFont().deriveFont(da_dataname_16.getFont().getStyle() | java.awt.Font.BOLD, da_dataname_16.getFont().getSize()+6));
        da_dataname_16.setForeground(new java.awt.Color(255, 255, 51));
        da_dataname_16.setText("Temperature");
        add(da_dataname_16);
        da_dataname_16.setBounds(20, 110, 320, 30);

        da_dataname_17.setFont(da_dataname_17.getFont().deriveFont(da_dataname_17.getFont().getStyle() | java.awt.Font.BOLD, da_dataname_17.getFont().getSize()+6));
        da_dataname_17.setForeground(new java.awt.Color(255, 255, 51));
        da_dataname_17.setText("Temperature");
        add(da_dataname_17);
        da_dataname_17.setBounds(20, 110, 320, 30);

        da_dataname_18.setFont(da_dataname_18.getFont().deriveFont(da_dataname_18.getFont().getStyle() | java.awt.Font.BOLD, da_dataname_18.getFont().getSize()+6));
        da_dataname_18.setForeground(new java.awt.Color(255, 255, 51));
        da_dataname_18.setText("Temperature");
        add(da_dataname_18);
        da_dataname_18.setBounds(20, 110, 320, 30);

        da_dataname_19.setFont(da_dataname_19.getFont().deriveFont(da_dataname_19.getFont().getStyle() | java.awt.Font.BOLD, da_dataname_19.getFont().getSize()+6));
        da_dataname_19.setForeground(new java.awt.Color(255, 255, 51));
        da_dataname_19.setText("Temperature");
        add(da_dataname_19);
        da_dataname_19.setBounds(20, 110, 320, 30);

        da_dataname_20.setFont(da_dataname_20.getFont().deriveFont(da_dataname_20.getFont().getStyle() | java.awt.Font.BOLD, da_dataname_20.getFont().getSize()+6));
        da_dataname_20.setForeground(new java.awt.Color(255, 255, 51));
        da_dataname_20.setText("Temperature");
        add(da_dataname_20);
        da_dataname_20.setBounds(20, 110, 320, 30);

        da_dataname_21.setFont(da_dataname_21.getFont().deriveFont(da_dataname_21.getFont().getStyle() | java.awt.Font.BOLD, da_dataname_21.getFont().getSize()+6));
        da_dataname_21.setForeground(new java.awt.Color(255, 255, 51));
        da_dataname_21.setText("Temperature");
        add(da_dataname_21);
        da_dataname_21.setBounds(20, 110, 320, 30);

        da_dataname_22.setFont(da_dataname_22.getFont().deriveFont(da_dataname_22.getFont().getStyle() | java.awt.Font.BOLD, da_dataname_22.getFont().getSize()+6));
        da_dataname_22.setForeground(new java.awt.Color(255, 255, 51));
        da_dataname_22.setText("Temperature");
        add(da_dataname_22);
        da_dataname_22.setBounds(20, 110, 320, 30);

        da_dataname_23.setFont(da_dataname_23.getFont().deriveFont(da_dataname_23.getFont().getStyle() | java.awt.Font.BOLD, da_dataname_23.getFont().getSize()+6));
        da_dataname_23.setForeground(new java.awt.Color(255, 255, 51));
        da_dataname_23.setText("Temperature");
        add(da_dataname_23);
        da_dataname_23.setBounds(20, 110, 320, 30);

        da_dataname_24.setFont(da_dataname_24.getFont().deriveFont(da_dataname_24.getFont().getStyle() | java.awt.Font.BOLD, da_dataname_24.getFont().getSize()+6));
        da_dataname_24.setForeground(new java.awt.Color(255, 255, 51));
        da_dataname_24.setText("Temperature");
        add(da_dataname_24);
        da_dataname_24.setBounds(20, 110, 320, 30);

        da_dataname_25.setFont(da_dataname_25.getFont().deriveFont(da_dataname_25.getFont().getStyle() | java.awt.Font.BOLD, da_dataname_25.getFont().getSize()+6));
        da_dataname_25.setForeground(new java.awt.Color(255, 255, 51));
        da_dataname_25.setText("Temperature");
        add(da_dataname_25);
        da_dataname_25.setBounds(20, 110, 320, 30);

        da_dataname_26.setFont(da_dataname_26.getFont().deriveFont(da_dataname_26.getFont().getStyle() | java.awt.Font.BOLD, da_dataname_26.getFont().getSize()+6));
        da_dataname_26.setForeground(new java.awt.Color(255, 255, 51));
        da_dataname_26.setText("Temperature");
        add(da_dataname_26);
        da_dataname_26.setBounds(20, 110, 320, 30);

        da_dataname_27.setFont(da_dataname_27.getFont().deriveFont(da_dataname_27.getFont().getStyle() | java.awt.Font.BOLD, da_dataname_27.getFont().getSize()+6));
        da_dataname_27.setForeground(new java.awt.Color(255, 255, 51));
        da_dataname_27.setText("Temperature");
        add(da_dataname_27);
        da_dataname_27.setBounds(20, 110, 320, 30);

        da_dataname_28.setFont(da_dataname_28.getFont().deriveFont(da_dataname_28.getFont().getStyle() | java.awt.Font.BOLD, da_dataname_28.getFont().getSize()+6));
        da_dataname_28.setForeground(new java.awt.Color(255, 255, 51));
        da_dataname_28.setText("Temperature");
        add(da_dataname_28);
        da_dataname_28.setBounds(20, 110, 320, 30);

        da_dataname_29.setFont(da_dataname_29.getFont().deriveFont(da_dataname_29.getFont().getStyle() | java.awt.Font.BOLD, da_dataname_29.getFont().getSize()+6));
        da_dataname_29.setForeground(new java.awt.Color(255, 255, 51));
        da_dataname_29.setText("Temperature");
        add(da_dataname_29);
        da_dataname_29.setBounds(20, 110, 320, 30);

        da_dataname_30.setFont(da_dataname_30.getFont().deriveFont(da_dataname_30.getFont().getStyle() | java.awt.Font.BOLD, da_dataname_30.getFont().getSize()+6));
        da_dataname_30.setForeground(new java.awt.Color(255, 255, 51));
        da_dataname_30.setText("Temperature");
        add(da_dataname_30);
        da_dataname_30.setBounds(20, 110, 320, 30);

        da_dataname_31.setFont(da_dataname_31.getFont().deriveFont(da_dataname_31.getFont().getStyle() | java.awt.Font.BOLD, da_dataname_31.getFont().getSize()+6));
        da_dataname_31.setForeground(new java.awt.Color(255, 255, 51));
        da_dataname_31.setText("Temperature");
        add(da_dataname_31);
        da_dataname_31.setBounds(20, 110, 320, 30);

        da_dataname_32.setFont(da_dataname_32.getFont().deriveFont(da_dataname_32.getFont().getStyle() | java.awt.Font.BOLD, da_dataname_32.getFont().getSize()+6));
        da_dataname_32.setForeground(new java.awt.Color(255, 255, 51));
        da_dataname_32.setText("Temperature");
        add(da_dataname_32);
        da_dataname_32.setBounds(20, 110, 320, 30);

        da_dataname_33.setFont(da_dataname_33.getFont().deriveFont(da_dataname_33.getFont().getStyle() | java.awt.Font.BOLD, da_dataname_33.getFont().getSize()+6));
        da_dataname_33.setForeground(new java.awt.Color(255, 255, 51));
        da_dataname_33.setText("Temperature");
        add(da_dataname_33);
        da_dataname_33.setBounds(20, 110, 320, 30);

        da_dataname_34.setFont(da_dataname_34.getFont().deriveFont(da_dataname_34.getFont().getStyle() | java.awt.Font.BOLD, da_dataname_34.getFont().getSize()+6));
        da_dataname_34.setForeground(new java.awt.Color(255, 255, 51));
        da_dataname_34.setText("Temperature");
        add(da_dataname_34);
        da_dataname_34.setBounds(20, 110, 320, 30);

        da_dataname_35.setFont(da_dataname_35.getFont().deriveFont(da_dataname_35.getFont().getStyle() | java.awt.Font.BOLD, da_dataname_35.getFont().getSize()+6));
        da_dataname_35.setForeground(new java.awt.Color(255, 255, 51));
        da_dataname_35.setText("Temperature");
        add(da_dataname_35);
        da_dataname_35.setBounds(20, 110, 320, 30);

        da_dataname_36.setFont(da_dataname_36.getFont().deriveFont(da_dataname_36.getFont().getStyle() | java.awt.Font.BOLD, da_dataname_36.getFont().getSize()+6));
        da_dataname_36.setForeground(new java.awt.Color(255, 255, 51));
        da_dataname_36.setText("Temperature");
        add(da_dataname_36);
        da_dataname_36.setBounds(20, 110, 320, 30);

        da_dataname_37.setFont(da_dataname_37.getFont().deriveFont(da_dataname_37.getFont().getStyle() | java.awt.Font.BOLD, da_dataname_37.getFont().getSize()+6));
        da_dataname_37.setForeground(new java.awt.Color(255, 255, 51));
        da_dataname_37.setText("Temperature");
        add(da_dataname_37);
        da_dataname_37.setBounds(20, 110, 320, 30);

        da_dataname_38.setFont(da_dataname_38.getFont().deriveFont(da_dataname_38.getFont().getStyle() | java.awt.Font.BOLD, da_dataname_38.getFont().getSize()+6));
        da_dataname_38.setForeground(new java.awt.Color(255, 255, 51));
        da_dataname_38.setText("Temperature");
        add(da_dataname_38);
        da_dataname_38.setBounds(20, 110, 320, 30);

        da_dataname_39.setFont(da_dataname_39.getFont().deriveFont(da_dataname_39.getFont().getStyle() | java.awt.Font.BOLD, da_dataname_39.getFont().getSize()+6));
        da_dataname_39.setForeground(new java.awt.Color(255, 255, 51));
        da_dataname_39.setText("Temperature");
        add(da_dataname_39);
        da_dataname_39.setBounds(20, 110, 320, 30);

        da_dataname_40.setFont(da_dataname_40.getFont().deriveFont(da_dataname_40.getFont().getStyle() | java.awt.Font.BOLD, da_dataname_40.getFont().getSize()+6));
        da_dataname_40.setForeground(new java.awt.Color(255, 255, 51));
        da_dataname_40.setText("Temperature");
        add(da_dataname_40);
        da_dataname_40.setBounds(20, 110, 320, 30);

        da_dataname_41.setFont(da_dataname_41.getFont().deriveFont(da_dataname_41.getFont().getStyle() | java.awt.Font.BOLD, da_dataname_41.getFont().getSize()+6));
        da_dataname_41.setForeground(new java.awt.Color(255, 255, 51));
        da_dataname_41.setText("Temperature");
        add(da_dataname_41);
        da_dataname_41.setBounds(20, 110, 320, 30);

        da_dataname_42.setFont(da_dataname_42.getFont().deriveFont(da_dataname_42.getFont().getStyle() | java.awt.Font.BOLD, da_dataname_42.getFont().getSize()+6));
        da_dataname_42.setForeground(new java.awt.Color(255, 255, 51));
        da_dataname_42.setText("Temperature");
        add(da_dataname_42);
        da_dataname_42.setBounds(20, 110, 320, 30);

        da_dataname_43.setFont(da_dataname_43.getFont().deriveFont(da_dataname_43.getFont().getStyle() | java.awt.Font.BOLD, da_dataname_43.getFont().getSize()+6));
        da_dataname_43.setForeground(new java.awt.Color(255, 255, 51));
        da_dataname_43.setText("Temperature");
        add(da_dataname_43);
        da_dataname_43.setBounds(20, 110, 320, 30);

        da_dataname_44.setFont(da_dataname_44.getFont().deriveFont(da_dataname_44.getFont().getStyle() | java.awt.Font.BOLD, da_dataname_44.getFont().getSize()+6));
        da_dataname_44.setForeground(new java.awt.Color(255, 255, 51));
        da_dataname_44.setText("Temperature");
        add(da_dataname_44);
        da_dataname_44.setBounds(20, 110, 320, 30);

        da_dataname_45.setFont(da_dataname_45.getFont().deriveFont(da_dataname_45.getFont().getStyle() | java.awt.Font.BOLD, da_dataname_45.getFont().getSize()+6));
        da_dataname_45.setForeground(new java.awt.Color(255, 255, 51));
        da_dataname_45.setText("Temperature");
        add(da_dataname_45);
        da_dataname_45.setBounds(20, 110, 320, 30);

        da_dataname_46.setFont(da_dataname_46.getFont().deriveFont(da_dataname_46.getFont().getStyle() | java.awt.Font.BOLD, da_dataname_46.getFont().getSize()+6));
        da_dataname_46.setForeground(new java.awt.Color(255, 255, 51));
        da_dataname_46.setText("Temperature");
        add(da_dataname_46);
        da_dataname_46.setBounds(20, 110, 320, 30);

        da_dataname_47.setFont(da_dataname_47.getFont().deriveFont(da_dataname_47.getFont().getStyle() | java.awt.Font.BOLD, da_dataname_47.getFont().getSize()+6));
        da_dataname_47.setForeground(new java.awt.Color(255, 255, 51));
        da_dataname_47.setText("Temperature");
        add(da_dataname_47);
        da_dataname_47.setBounds(20, 110, 320, 30);

        da_dataname_48.setFont(da_dataname_48.getFont().deriveFont(da_dataname_48.getFont().getStyle() | java.awt.Font.BOLD, da_dataname_48.getFont().getSize()+6));
        da_dataname_48.setForeground(new java.awt.Color(255, 255, 51));
        da_dataname_48.setText("Temperature");
        add(da_dataname_48);
        da_dataname_48.setBounds(20, 110, 320, 30);

        da_datavalue_02.setFont(da_datavalue_02.getFont().deriveFont(da_datavalue_02.getFont().getStyle() | java.awt.Font.BOLD, da_datavalue_02.getFont().getSize()+36));
        da_datavalue_02.setForeground(new java.awt.Color(255, 0, 51));
        da_datavalue_02.setText("1000.09");
        add(da_datavalue_02);
        da_datavalue_02.setBounds(60, 150, 300, 60);

        da_datavalue_03.setFont(da_datavalue_03.getFont().deriveFont(da_datavalue_03.getFont().getStyle() | java.awt.Font.BOLD, da_datavalue_03.getFont().getSize()+36));
        da_datavalue_03.setForeground(new java.awt.Color(255, 0, 51));
        da_datavalue_03.setText("1000.09");
        add(da_datavalue_03);
        da_datavalue_03.setBounds(60, 150, 300, 60);

        da_datavalue_04.setFont(da_datavalue_04.getFont().deriveFont(da_datavalue_04.getFont().getStyle() | java.awt.Font.BOLD, da_datavalue_04.getFont().getSize()+36));
        da_datavalue_04.setForeground(new java.awt.Color(255, 0, 51));
        da_datavalue_04.setText("1000.09");
        add(da_datavalue_04);
        da_datavalue_04.setBounds(60, 150, 300, 60);

        da_datavalue_05.setFont(da_datavalue_05.getFont().deriveFont(da_datavalue_05.getFont().getStyle() | java.awt.Font.BOLD, da_datavalue_05.getFont().getSize()+36));
        da_datavalue_05.setForeground(new java.awt.Color(255, 0, 51));
        da_datavalue_05.setText("1000.09");
        add(da_datavalue_05);
        da_datavalue_05.setBounds(60, 150, 300, 60);

        da_datavalue_06.setFont(da_datavalue_06.getFont().deriveFont(da_datavalue_06.getFont().getStyle() | java.awt.Font.BOLD, da_datavalue_06.getFont().getSize()+36));
        da_datavalue_06.setForeground(new java.awt.Color(255, 0, 51));
        da_datavalue_06.setText("1000.09");
        add(da_datavalue_06);
        da_datavalue_06.setBounds(60, 150, 300, 60);

        da_datavalue_07.setFont(da_datavalue_07.getFont().deriveFont(da_datavalue_07.getFont().getStyle() | java.awt.Font.BOLD, da_datavalue_07.getFont().getSize()+36));
        da_datavalue_07.setForeground(new java.awt.Color(255, 0, 51));
        da_datavalue_07.setText("1000.09");
        add(da_datavalue_07);
        da_datavalue_07.setBounds(60, 150, 300, 60);

        da_datavalue_08.setFont(da_datavalue_08.getFont().deriveFont(da_datavalue_08.getFont().getStyle() | java.awt.Font.BOLD, da_datavalue_08.getFont().getSize()+36));
        da_datavalue_08.setForeground(new java.awt.Color(255, 0, 51));
        da_datavalue_08.setText("1000.09");
        add(da_datavalue_08);
        da_datavalue_08.setBounds(60, 150, 300, 60);

        da_datavalue_09.setFont(da_datavalue_09.getFont().deriveFont(da_datavalue_09.getFont().getStyle() | java.awt.Font.BOLD, da_datavalue_09.getFont().getSize()+36));
        da_datavalue_09.setForeground(new java.awt.Color(255, 0, 51));
        da_datavalue_09.setText("1000.09");
        add(da_datavalue_09);
        da_datavalue_09.setBounds(60, 150, 300, 60);

        da_datavalue_10.setFont(da_datavalue_10.getFont().deriveFont(da_datavalue_10.getFont().getStyle() | java.awt.Font.BOLD, da_datavalue_10.getFont().getSize()+36));
        da_datavalue_10.setForeground(new java.awt.Color(255, 0, 51));
        da_datavalue_10.setText("1000.09");
        add(da_datavalue_10);
        da_datavalue_10.setBounds(60, 150, 300, 60);

        da_datavalue_11.setFont(da_datavalue_11.getFont().deriveFont(da_datavalue_11.getFont().getStyle() | java.awt.Font.BOLD, da_datavalue_11.getFont().getSize()+36));
        da_datavalue_11.setForeground(new java.awt.Color(255, 0, 51));
        da_datavalue_11.setText("1000.09");
        add(da_datavalue_11);
        da_datavalue_11.setBounds(60, 150, 300, 60);

        da_datavalue_12.setFont(da_datavalue_12.getFont().deriveFont(da_datavalue_12.getFont().getStyle() | java.awt.Font.BOLD, da_datavalue_12.getFont().getSize()+36));
        da_datavalue_12.setForeground(new java.awt.Color(255, 0, 51));
        da_datavalue_12.setText("1000.09");
        add(da_datavalue_12);
        da_datavalue_12.setBounds(60, 150, 300, 60);

        da_datavalue_13.setFont(da_datavalue_13.getFont().deriveFont(da_datavalue_13.getFont().getStyle() | java.awt.Font.BOLD, da_datavalue_13.getFont().getSize()+36));
        da_datavalue_13.setForeground(new java.awt.Color(255, 0, 51));
        da_datavalue_13.setText("1000.09");
        add(da_datavalue_13);
        da_datavalue_13.setBounds(60, 150, 300, 60);

        da_datavalue_14.setFont(da_datavalue_14.getFont().deriveFont(da_datavalue_14.getFont().getStyle() | java.awt.Font.BOLD, da_datavalue_14.getFont().getSize()+36));
        da_datavalue_14.setForeground(new java.awt.Color(255, 0, 51));
        da_datavalue_14.setText("1000.09");
        add(da_datavalue_14);
        da_datavalue_14.setBounds(60, 150, 300, 60);

        da_datavalue_15.setFont(da_datavalue_15.getFont().deriveFont(da_datavalue_15.getFont().getStyle() | java.awt.Font.BOLD, da_datavalue_15.getFont().getSize()+36));
        da_datavalue_15.setForeground(new java.awt.Color(255, 0, 51));
        da_datavalue_15.setText("1000.09");
        add(da_datavalue_15);
        da_datavalue_15.setBounds(60, 150, 300, 60);

        da_datavalue_16.setFont(da_datavalue_16.getFont().deriveFont(da_datavalue_16.getFont().getStyle() | java.awt.Font.BOLD, da_datavalue_16.getFont().getSize()+36));
        da_datavalue_16.setForeground(new java.awt.Color(255, 0, 51));
        da_datavalue_16.setText("1000.09");
        add(da_datavalue_16);
        da_datavalue_16.setBounds(60, 150, 300, 60);

        da_datavalue_17.setFont(da_datavalue_17.getFont().deriveFont(da_datavalue_17.getFont().getStyle() | java.awt.Font.BOLD, da_datavalue_17.getFont().getSize()+36));
        da_datavalue_17.setForeground(new java.awt.Color(255, 0, 51));
        da_datavalue_17.setText("1000.09");
        add(da_datavalue_17);
        da_datavalue_17.setBounds(60, 150, 300, 60);

        da_datavalue_18.setFont(da_datavalue_18.getFont().deriveFont(da_datavalue_18.getFont().getStyle() | java.awt.Font.BOLD, da_datavalue_18.getFont().getSize()+36));
        da_datavalue_18.setForeground(new java.awt.Color(255, 0, 51));
        da_datavalue_18.setText("1000.09");
        add(da_datavalue_18);
        da_datavalue_18.setBounds(60, 150, 300, 60);

        da_datavalue_19.setFont(da_datavalue_19.getFont().deriveFont(da_datavalue_19.getFont().getStyle() | java.awt.Font.BOLD, da_datavalue_19.getFont().getSize()+36));
        da_datavalue_19.setForeground(new java.awt.Color(255, 0, 51));
        da_datavalue_19.setText("1000.09");
        add(da_datavalue_19);
        da_datavalue_19.setBounds(60, 150, 300, 60);

        da_datavalue_20.setFont(da_datavalue_20.getFont().deriveFont(da_datavalue_20.getFont().getStyle() | java.awt.Font.BOLD, da_datavalue_20.getFont().getSize()+36));
        da_datavalue_20.setForeground(new java.awt.Color(255, 0, 51));
        da_datavalue_20.setText("1000.09");
        add(da_datavalue_20);
        da_datavalue_20.setBounds(60, 150, 300, 60);

        da_datavalue_21.setFont(da_datavalue_21.getFont().deriveFont(da_datavalue_21.getFont().getStyle() | java.awt.Font.BOLD, da_datavalue_21.getFont().getSize()+36));
        da_datavalue_21.setForeground(new java.awt.Color(255, 0, 51));
        da_datavalue_21.setText("1000.09");
        add(da_datavalue_21);
        da_datavalue_21.setBounds(60, 150, 300, 60);

        da_datavalue_22.setFont(da_datavalue_22.getFont().deriveFont(da_datavalue_22.getFont().getStyle() | java.awt.Font.BOLD, da_datavalue_22.getFont().getSize()+36));
        da_datavalue_22.setForeground(new java.awt.Color(255, 0, 51));
        da_datavalue_22.setText("1000.09");
        add(da_datavalue_22);
        da_datavalue_22.setBounds(60, 150, 300, 60);

        da_datavalue_23.setFont(da_datavalue_23.getFont().deriveFont(da_datavalue_23.getFont().getStyle() | java.awt.Font.BOLD, da_datavalue_23.getFont().getSize()+36));
        da_datavalue_23.setForeground(new java.awt.Color(255, 0, 51));
        da_datavalue_23.setText("1000.09");
        add(da_datavalue_23);
        da_datavalue_23.setBounds(60, 150, 300, 60);

        da_datavalue_24.setFont(da_datavalue_24.getFont().deriveFont(da_datavalue_24.getFont().getStyle() | java.awt.Font.BOLD, da_datavalue_24.getFont().getSize()+36));
        da_datavalue_24.setForeground(new java.awt.Color(255, 0, 51));
        da_datavalue_24.setText("1000.09");
        add(da_datavalue_24);
        da_datavalue_24.setBounds(60, 150, 300, 60);

        da_datavalue_25.setFont(da_datavalue_25.getFont().deriveFont(da_datavalue_25.getFont().getStyle() | java.awt.Font.BOLD, da_datavalue_25.getFont().getSize()+36));
        da_datavalue_25.setForeground(new java.awt.Color(255, 0, 51));
        da_datavalue_25.setText("1000.09");
        add(da_datavalue_25);
        da_datavalue_25.setBounds(60, 150, 300, 60);

        da_datavalue_26.setFont(da_datavalue_26.getFont().deriveFont(da_datavalue_26.getFont().getStyle() | java.awt.Font.BOLD, da_datavalue_26.getFont().getSize()+36));
        da_datavalue_26.setForeground(new java.awt.Color(255, 0, 51));
        da_datavalue_26.setText("1000.09");
        add(da_datavalue_26);
        da_datavalue_26.setBounds(60, 150, 300, 60);

        da_datavalue_27.setFont(da_datavalue_27.getFont().deriveFont(da_datavalue_27.getFont().getStyle() | java.awt.Font.BOLD, da_datavalue_27.getFont().getSize()+36));
        da_datavalue_27.setForeground(new java.awt.Color(255, 0, 51));
        da_datavalue_27.setText("1000.09");
        add(da_datavalue_27);
        da_datavalue_27.setBounds(60, 150, 300, 60);

        da_datavalue_28.setFont(da_datavalue_28.getFont().deriveFont(da_datavalue_28.getFont().getStyle() | java.awt.Font.BOLD, da_datavalue_28.getFont().getSize()+36));
        da_datavalue_28.setForeground(new java.awt.Color(255, 0, 51));
        da_datavalue_28.setText("1000.09");
        add(da_datavalue_28);
        da_datavalue_28.setBounds(60, 150, 300, 60);

        da_datavalue_29.setFont(da_datavalue_29.getFont().deriveFont(da_datavalue_29.getFont().getStyle() | java.awt.Font.BOLD, da_datavalue_29.getFont().getSize()+36));
        da_datavalue_29.setForeground(new java.awt.Color(255, 0, 51));
        da_datavalue_29.setText("1000.09");
        add(da_datavalue_29);
        da_datavalue_29.setBounds(60, 150, 300, 60);

        da_datavalue_30.setFont(da_datavalue_30.getFont().deriveFont(da_datavalue_30.getFont().getStyle() | java.awt.Font.BOLD, da_datavalue_30.getFont().getSize()+36));
        da_datavalue_30.setForeground(new java.awt.Color(255, 0, 51));
        da_datavalue_30.setText("1000.09");
        add(da_datavalue_30);
        da_datavalue_30.setBounds(60, 150, 300, 60);

        da_datavalue_31.setFont(da_datavalue_31.getFont().deriveFont(da_datavalue_31.getFont().getStyle() | java.awt.Font.BOLD, da_datavalue_31.getFont().getSize()+36));
        da_datavalue_31.setForeground(new java.awt.Color(255, 0, 51));
        da_datavalue_31.setText("1000.09");
        add(da_datavalue_31);
        da_datavalue_31.setBounds(60, 150, 300, 60);

        da_datavalue_32.setFont(da_datavalue_32.getFont().deriveFont(da_datavalue_32.getFont().getStyle() | java.awt.Font.BOLD, da_datavalue_32.getFont().getSize()+36));
        da_datavalue_32.setForeground(new java.awt.Color(255, 0, 51));
        da_datavalue_32.setText("1000.09");
        add(da_datavalue_32);
        da_datavalue_32.setBounds(60, 150, 300, 60);

        da_datavalue_33.setFont(da_datavalue_33.getFont().deriveFont(da_datavalue_33.getFont().getStyle() | java.awt.Font.BOLD, da_datavalue_33.getFont().getSize()+36));
        da_datavalue_33.setForeground(new java.awt.Color(255, 0, 51));
        da_datavalue_33.setText("1000.09");
        add(da_datavalue_33);
        da_datavalue_33.setBounds(60, 150, 300, 60);

        da_datavalue_34.setFont(da_datavalue_34.getFont().deriveFont(da_datavalue_34.getFont().getStyle() | java.awt.Font.BOLD, da_datavalue_34.getFont().getSize()+36));
        da_datavalue_34.setForeground(new java.awt.Color(255, 0, 51));
        da_datavalue_34.setText("1000.09");
        add(da_datavalue_34);
        da_datavalue_34.setBounds(60, 150, 300, 60);

        da_datavalue_35.setFont(da_datavalue_35.getFont().deriveFont(da_datavalue_35.getFont().getStyle() | java.awt.Font.BOLD, da_datavalue_35.getFont().getSize()+36));
        da_datavalue_35.setForeground(new java.awt.Color(255, 0, 51));
        da_datavalue_35.setText("1000.09");
        add(da_datavalue_35);
        da_datavalue_35.setBounds(60, 150, 300, 60);

        da_datavalue_36.setFont(da_datavalue_36.getFont().deriveFont(da_datavalue_36.getFont().getStyle() | java.awt.Font.BOLD, da_datavalue_36.getFont().getSize()+36));
        da_datavalue_36.setForeground(new java.awt.Color(255, 0, 51));
        da_datavalue_36.setText("1000.09");
        add(da_datavalue_36);
        da_datavalue_36.setBounds(60, 150, 300, 60);

        da_datavalue_37.setFont(da_datavalue_37.getFont().deriveFont(da_datavalue_37.getFont().getStyle() | java.awt.Font.BOLD, da_datavalue_37.getFont().getSize()+36));
        da_datavalue_37.setForeground(new java.awt.Color(255, 0, 51));
        da_datavalue_37.setText("1000.09");
        add(da_datavalue_37);
        da_datavalue_37.setBounds(60, 150, 300, 60);

        da_datavalue_38.setFont(da_datavalue_38.getFont().deriveFont(da_datavalue_38.getFont().getStyle() | java.awt.Font.BOLD, da_datavalue_38.getFont().getSize()+36));
        da_datavalue_38.setForeground(new java.awt.Color(255, 0, 51));
        da_datavalue_38.setText("1000.09");
        add(da_datavalue_38);
        da_datavalue_38.setBounds(60, 150, 300, 60);

        da_datavalue_39.setFont(da_datavalue_39.getFont().deriveFont(da_datavalue_39.getFont().getStyle() | java.awt.Font.BOLD, da_datavalue_39.getFont().getSize()+36));
        da_datavalue_39.setForeground(new java.awt.Color(255, 0, 51));
        da_datavalue_39.setText("1000.09");
        add(da_datavalue_39);
        da_datavalue_39.setBounds(60, 150, 300, 60);

        da_datavalue_40.setFont(da_datavalue_40.getFont().deriveFont(da_datavalue_40.getFont().getStyle() | java.awt.Font.BOLD, da_datavalue_40.getFont().getSize()+36));
        da_datavalue_40.setForeground(new java.awt.Color(255, 0, 51));
        da_datavalue_40.setText("1000.09");
        add(da_datavalue_40);
        da_datavalue_40.setBounds(60, 150, 300, 60);

        da_datavalue_41.setFont(da_datavalue_41.getFont().deriveFont(da_datavalue_41.getFont().getStyle() | java.awt.Font.BOLD, da_datavalue_41.getFont().getSize()+36));
        da_datavalue_41.setForeground(new java.awt.Color(255, 0, 51));
        da_datavalue_41.setText("1000.09");
        add(da_datavalue_41);
        da_datavalue_41.setBounds(60, 150, 300, 60);

        da_datavalue_42.setFont(da_datavalue_42.getFont().deriveFont(da_datavalue_42.getFont().getStyle() | java.awt.Font.BOLD, da_datavalue_42.getFont().getSize()+36));
        da_datavalue_42.setForeground(new java.awt.Color(255, 0, 51));
        da_datavalue_42.setText("1000.09");
        add(da_datavalue_42);
        da_datavalue_42.setBounds(60, 150, 300, 60);

        da_datavalue_43.setFont(da_datavalue_43.getFont().deriveFont(da_datavalue_43.getFont().getStyle() | java.awt.Font.BOLD, da_datavalue_43.getFont().getSize()+36));
        da_datavalue_43.setForeground(new java.awt.Color(255, 0, 51));
        da_datavalue_43.setText("1000.09");
        add(da_datavalue_43);
        da_datavalue_43.setBounds(60, 150, 300, 60);

        da_datavalue_44.setFont(da_datavalue_44.getFont().deriveFont(da_datavalue_44.getFont().getStyle() | java.awt.Font.BOLD, da_datavalue_44.getFont().getSize()+36));
        da_datavalue_44.setForeground(new java.awt.Color(255, 0, 51));
        da_datavalue_44.setText("1000.09");
        add(da_datavalue_44);
        da_datavalue_44.setBounds(60, 150, 300, 60);

        da_datavalue_45.setFont(da_datavalue_45.getFont().deriveFont(da_datavalue_45.getFont().getStyle() | java.awt.Font.BOLD, da_datavalue_45.getFont().getSize()+36));
        da_datavalue_45.setForeground(new java.awt.Color(255, 0, 51));
        da_datavalue_45.setText("1000.09");
        add(da_datavalue_45);
        da_datavalue_45.setBounds(60, 150, 300, 60);

        da_datavalue_46.setFont(da_datavalue_46.getFont().deriveFont(da_datavalue_46.getFont().getStyle() | java.awt.Font.BOLD, da_datavalue_46.getFont().getSize()+36));
        da_datavalue_46.setForeground(new java.awt.Color(255, 0, 51));
        da_datavalue_46.setText("1000.09");
        add(da_datavalue_46);
        da_datavalue_46.setBounds(60, 150, 300, 60);

        da_datavalue_47.setFont(da_datavalue_47.getFont().deriveFont(da_datavalue_47.getFont().getStyle() | java.awt.Font.BOLD, da_datavalue_47.getFont().getSize()+36));
        da_datavalue_47.setForeground(new java.awt.Color(255, 0, 51));
        da_datavalue_47.setText("1000.09");
        add(da_datavalue_47);
        da_datavalue_47.setBounds(60, 150, 300, 60);

        da_datavalue_48.setFont(da_datavalue_48.getFont().deriveFont(da_datavalue_48.getFont().getStyle() | java.awt.Font.BOLD, da_datavalue_48.getFont().getSize()+36));
        da_datavalue_48.setForeground(new java.awt.Color(255, 0, 51));
        da_datavalue_48.setText("1000.09");
        add(da_datavalue_48);
        da_datavalue_48.setBounds(60, 150, 300, 60);

        da_xlabel_01.setFont(da_xlabel_01.getFont());
        da_xlabel_01.setText("text label");
        add(da_xlabel_01);
        da_xlabel_01.setBounds(90, 230, 120, 15);

        da_xlabel_02.setFont(da_xlabel_02.getFont());
        da_xlabel_02.setText("text label");
        add(da_xlabel_02);
        da_xlabel_02.setBounds(90, 230, 120, 15);

        da_xlabel_03.setFont(da_xlabel_03.getFont());
        da_xlabel_03.setText("text label");
        add(da_xlabel_03);
        da_xlabel_03.setBounds(90, 230, 120, 15);

        da_xlabel_04.setFont(da_xlabel_04.getFont());
        da_xlabel_04.setText("text label");
        add(da_xlabel_04);
        da_xlabel_04.setBounds(90, 230, 120, 15);

        da_xlabel_05.setFont(da_xlabel_05.getFont());
        da_xlabel_05.setText("text label");
        add(da_xlabel_05);
        da_xlabel_05.setBounds(90, 230, 120, 15);

        da_xlabel_06.setFont(da_xlabel_06.getFont());
        da_xlabel_06.setText("text label");
        add(da_xlabel_06);
        da_xlabel_06.setBounds(90, 230, 120, 15);

        da_xlabel_07.setFont(da_xlabel_07.getFont());
        da_xlabel_07.setText("text label");
        add(da_xlabel_07);
        da_xlabel_07.setBounds(90, 230, 120, 15);

        da_xlabel_08.setFont(da_xlabel_08.getFont());
        da_xlabel_08.setText("text label");
        add(da_xlabel_08);
        da_xlabel_08.setBounds(90, 230, 120, 15);

        da_xlabel_09.setFont(da_xlabel_09.getFont());
        da_xlabel_09.setText("text label");
        add(da_xlabel_09);
        da_xlabel_09.setBounds(90, 230, 120, 15);

        da_xlabel_10.setFont(da_xlabel_10.getFont());
        da_xlabel_10.setText("text label");
        add(da_xlabel_10);
        da_xlabel_10.setBounds(90, 230, 120, 15);
    }

    public javax.swing.JLabel da_dataname_01;
    public javax.swing.JLabel da_dataname_02;
    public javax.swing.JLabel da_dataname_03;
    public javax.swing.JLabel da_dataname_04;
    public javax.swing.JLabel da_dataname_05;
    public javax.swing.JLabel da_dataname_06;
    public javax.swing.JLabel da_dataname_07;
    public javax.swing.JLabel da_dataname_08;
    public javax.swing.JLabel da_dataname_09;
    public javax.swing.JLabel da_dataname_10;
    public javax.swing.JLabel da_dataname_11;
    public javax.swing.JLabel da_dataname_12;
    public javax.swing.JLabel da_dataname_13;
    public javax.swing.JLabel da_dataname_14;
    public javax.swing.JLabel da_dataname_15;
    public javax.swing.JLabel da_dataname_16;
    public javax.swing.JLabel da_dataname_17;
    public javax.swing.JLabel da_dataname_18;
    public javax.swing.JLabel da_dataname_19;
    public javax.swing.JLabel da_dataname_20;
    public javax.swing.JLabel da_dataname_21;
    public javax.swing.JLabel da_dataname_22;
    public javax.swing.JLabel da_dataname_23;
    public javax.swing.JLabel da_dataname_24;
    public javax.swing.JLabel da_dataname_25;
    public javax.swing.JLabel da_dataname_26;
    public javax.swing.JLabel da_dataname_27;
    public javax.swing.JLabel da_dataname_28;
    public javax.swing.JLabel da_dataname_29;
    public javax.swing.JLabel da_dataname_30;
    public javax.swing.JLabel da_dataname_31;
    public javax.swing.JLabel da_dataname_32;
    public javax.swing.JLabel da_dataname_33;
    public javax.swing.JLabel da_dataname_34;
    public javax.swing.JLabel da_dataname_35;
    public javax.swing.JLabel da_dataname_36;
    public javax.swing.JLabel da_dataname_37;
    public javax.swing.JLabel da_dataname_38;
    public javax.swing.JLabel da_dataname_39;
    public javax.swing.JLabel da_dataname_40;
    public javax.swing.JLabel da_dataname_41;
    public javax.swing.JLabel da_dataname_42;
    public javax.swing.JLabel da_dataname_43;
    public javax.swing.JLabel da_dataname_44;
    public javax.swing.JLabel da_dataname_45;
    public javax.swing.JLabel da_dataname_46;
    public javax.swing.JLabel da_dataname_47;
    public javax.swing.JLabel da_dataname_48;
    public javax.swing.JLabel da_datavalue_01;
    public javax.swing.JLabel da_datavalue_02;
    public javax.swing.JLabel da_datavalue_03;
    public javax.swing.JLabel da_datavalue_04;
    public javax.swing.JLabel da_datavalue_05;
    public javax.swing.JLabel da_datavalue_06;
    public javax.swing.JLabel da_datavalue_07;
    public javax.swing.JLabel da_datavalue_08;
    public javax.swing.JLabel da_datavalue_09;
    public javax.swing.JLabel da_datavalue_10;
    public javax.swing.JLabel da_datavalue_11;
    public javax.swing.JLabel da_datavalue_12;
    public javax.swing.JLabel da_datavalue_13;
    public javax.swing.JLabel da_datavalue_14;
    public javax.swing.JLabel da_datavalue_15;
    public javax.swing.JLabel da_datavalue_16;
    public javax.swing.JLabel da_datavalue_17;
    public javax.swing.JLabel da_datavalue_18;
    public javax.swing.JLabel da_datavalue_19;
    public javax.swing.JLabel da_datavalue_20;
    public javax.swing.JLabel da_datavalue_21;
    public javax.swing.JLabel da_datavalue_22;
    public javax.swing.JLabel da_datavalue_23;
    public javax.swing.JLabel da_datavalue_24;
    public javax.swing.JLabel da_datavalue_25;
    public javax.swing.JLabel da_datavalue_26;
    public javax.swing.JLabel da_datavalue_27;
    public javax.swing.JLabel da_datavalue_28;
    public javax.swing.JLabel da_datavalue_29;
    public javax.swing.JLabel da_datavalue_30;
    public javax.swing.JLabel da_datavalue_31;
    public javax.swing.JLabel da_datavalue_32;
    public javax.swing.JLabel da_datavalue_33;
    public javax.swing.JLabel da_datavalue_34;
    public javax.swing.JLabel da_datavalue_35;
    public javax.swing.JLabel da_datavalue_36;
    public javax.swing.JLabel da_datavalue_37;
    public javax.swing.JLabel da_datavalue_38;
    public javax.swing.JLabel da_datavalue_39;
    public javax.swing.JLabel da_datavalue_40;
    public javax.swing.JLabel da_datavalue_41;
    public javax.swing.JLabel da_datavalue_42;
    public javax.swing.JLabel da_datavalue_43;
    public javax.swing.JLabel da_datavalue_44;
    public javax.swing.JLabel da_datavalue_45;
    public javax.swing.JLabel da_datavalue_46;
    public javax.swing.JLabel da_datavalue_47;
    public javax.swing.JLabel da_datavalue_48;
    public javax.swing.JLabel da_device_01;
    public javax.swing.JLabel da_device_02;
    public javax.swing.JLabel da_device_03;
    public javax.swing.JLabel da_device_04;
    public javax.swing.JLabel da_device_05;
    public javax.swing.JLabel da_device_06;
    public javax.swing.JLabel da_device_07;
    public javax.swing.JLabel da_device_08;
    public javax.swing.JLabel da_device_09;
    public javax.swing.JLabel da_device_10;
    public javax.swing.JLabel da_device_11;
    public javax.swing.JLabel da_device_12;
    public javax.swing.JLabel da_device_13;
    public javax.swing.JLabel da_device_14;
    public javax.swing.JLabel da_device_15;
    public javax.swing.JLabel da_device_16;
    public javax.swing.JLabel da_device_17;
    public javax.swing.JLabel da_device_18;
    public javax.swing.JLabel da_device_19;
    public javax.swing.JLabel da_device_20;
    public javax.swing.JLabel da_device_21;
    public javax.swing.JLabel da_device_22;
    public javax.swing.JLabel da_device_23;
    public javax.swing.JLabel da_device_24;
    public javax.swing.JLabel da_device_25;
    public javax.swing.JLabel da_device_26;
    public javax.swing.JLabel da_device_27;
    public javax.swing.JLabel da_device_28;
    public javax.swing.JLabel da_device_29;
    public javax.swing.JLabel da_device_30;
    public javax.swing.JLabel da_device_31;
    public javax.swing.JLabel da_device_32;
    public javax.swing.JLabel da_station_01;
    public javax.swing.JLabel da_station_02;
    public javax.swing.JLabel da_station_03;
    public javax.swing.JLabel da_station_04;
    public javax.swing.JLabel da_station_05;
    public javax.swing.JLabel da_station_06;
    public javax.swing.JLabel da_station_07;
    public javax.swing.JLabel da_station_08;
    public javax.swing.JLabel da_station_09;
    public javax.swing.JLabel da_station_10;
    public javax.swing.JLabel da_station_11;
    public javax.swing.JLabel da_station_12;
    public javax.swing.JLabel da_station_13;
    public javax.swing.JLabel da_station_14;
    public javax.swing.JLabel da_station_15;
    public javax.swing.JLabel da_station_16;
    public javax.swing.JLabel da_xlabel_01;
    public javax.swing.JLabel da_xlabel_02;
    public javax.swing.JLabel da_xlabel_03;
    public javax.swing.JLabel da_xlabel_04;
    public javax.swing.JLabel da_xlabel_05;
    public javax.swing.JLabel da_xlabel_06;
    public javax.swing.JLabel da_xlabel_07;
    public javax.swing.JLabel da_xlabel_08;
    public javax.swing.JLabel da_xlabel_09;
    public javax.swing.JLabel da_xlabel_10;

}