
package ci;

import javax.swing.DefaultListModel;

/**
 *
 * @author peter
 */
public class CIFramePanel2 extends javax.swing.JPanel {

CrInstrument instrument;
    public DefaultListModel stationListModel = new DefaultListModel();
    public CIDataPanel dataPanel;
    public CIFramePanel2(CrInstrument instrument) {
        initComponents();
        this.instrument=instrument;
        dataPanel=new CIDataPanel(this.instrument);
        add(dataPanel);
        dataPanel.setBounds(170, 330, 380, 280);

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void initComponents() {

        buttonGroup01 = new javax.swing.ButtonGroup();
        buttonGroup02 = new javax.swing.ButtonGroup();
        buttonGroup03 = new javax.swing.ButtonGroup();
        buttonGroup04 = new javax.swing.ButtonGroup();
        buttonGroup05 = new javax.swing.ButtonGroup();
        buttonGroup06 = new javax.swing.ButtonGroup();
        buttonGroup07 = new javax.swing.ButtonGroup();
        buttonGroup08 = new javax.swing.ButtonGroup();
        buttonGroup09 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        timeLabel = new javax.swing.JLabel();
        button03 = new javax.swing.JButton();
        button04 = new javax.swing.JButton();
        button05 = new javax.swing.JButton();
        button06 = new javax.swing.JButton();
        button07 = new javax.swing.JButton();
        button08 = new javax.swing.JButton();
        button09 = new javax.swing.JButton();
        button10 = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();
        button02 = new javax.swing.JButton();
        btnConnect = new javax.swing.JButton();
        statusLabel = new javax.swing.JLabel();
        lightPanel = new ci.LightPanel();
        textLabel01 = new javax.swing.JLabel();
        comboBox01 = new javax.swing.JComboBox();
        textField01 = new javax.swing.JTextField();
        textLabel02 = new javax.swing.JLabel();
        textLabel03 = new javax.swing.JLabel();
        textLabel04 = new javax.swing.JLabel();
        textLabel05 = new javax.swing.JLabel();
        textLabel06 = new javax.swing.JLabel();
        textLabel07 = new javax.swing.JLabel();
        textLabel08 = new javax.swing.JLabel();
        textLabel09 = new javax.swing.JLabel();
        textLabel10 = new javax.swing.JLabel();
        textLabel11 = new javax.swing.JLabel();
        textLabel12 = new javax.swing.JLabel();
        textLabel13 = new javax.swing.JLabel();
        textLabel14 = new javax.swing.JLabel();
        textLabel15 = new javax.swing.JLabel();
        textLabel16 = new javax.swing.JLabel();
        textLabel17 = new javax.swing.JLabel();
        textLabel18 = new javax.swing.JLabel();
        textLabel19 = new javax.swing.JLabel();
        textLabel20 = new javax.swing.JLabel();
        textLabel21 = new javax.swing.JLabel();
        textLabel22 = new javax.swing.JLabel();
        textLabel23 = new javax.swing.JLabel();
        textLabel24 = new javax.swing.JLabel();
        textLabel25 = new javax.swing.JLabel();
        textLabel26 = new javax.swing.JLabel();
        textLabel27 = new javax.swing.JLabel();
        textLabel28 = new javax.swing.JLabel();
        textLabel29 = new javax.swing.JLabel();
        textLabel30 = new javax.swing.JLabel();
        comboBox02 = new javax.swing.JComboBox();
        comboBox03 = new javax.swing.JComboBox();
        comboBox04 = new javax.swing.JComboBox();
        comboBox05 = new javax.swing.JComboBox();
        comboBox06 = new javax.swing.JComboBox();
        comboBox07 = new javax.swing.JComboBox();
        comboBox08 = new javax.swing.JComboBox();
        comboBox09 = new javax.swing.JComboBox();
        comboBox10 = new javax.swing.JComboBox();
        comboBox11 = new javax.swing.JComboBox();
        comboBox12 = new javax.swing.JComboBox();
        comboBox13 = new javax.swing.JComboBox();
        comboBox14 = new javax.swing.JComboBox();
        comboBox15 = new javax.swing.JComboBox();
        comboBox16 = new javax.swing.JComboBox();
        comboBox17 = new javax.swing.JComboBox();
        comboBox18 = new javax.swing.JComboBox();
        comboBox19 = new javax.swing.JComboBox();
        comboBox20 = new javax.swing.JComboBox();
        textField02 = new javax.swing.JTextField();
        textField03 = new javax.swing.JTextField();
        textField04 = new javax.swing.JTextField();
        textField05 = new javax.swing.JTextField();
        textField06 = new javax.swing.JTextField();
        textField07 = new javax.swing.JTextField();
        textField08 = new javax.swing.JTextField();
        textField09 = new javax.swing.JTextField();
        textField10 = new javax.swing.JTextField();
        textField11 = new javax.swing.JTextField();
        textField12 = new javax.swing.JTextField();
        textField13 = new javax.swing.JTextField();
        textField14 = new javax.swing.JTextField();
        textField15 = new javax.swing.JTextField();
        textField16 = new javax.swing.JTextField();
        textField17 = new javax.swing.JTextField();
        textField18 = new javax.swing.JTextField();
        textField19 = new javax.swing.JTextField();
        textField20 = new javax.swing.JTextField();
        textField21 = new javax.swing.JTextField();
        textField22 = new javax.swing.JTextField();
        textField23 = new javax.swing.JTextField();
        textField24 = new javax.swing.JTextField();
        textField25 = new javax.swing.JTextField();
        textField26 = new javax.swing.JTextField();
        textField27 = new javax.swing.JTextField();
        textField28 = new javax.swing.JTextField();
        textField29 = new javax.swing.JTextField();
        textField30 = new javax.swing.JTextField();
        button25 = new javax.swing.JButton();
        button26 = new javax.swing.JButton();
        button27 = new javax.swing.JButton();
        button28 = new javax.swing.JButton();
        button29 = new javax.swing.JButton();
        button30 = new javax.swing.JButton();
        button11 = new javax.swing.JButton();
        button12 = new javax.swing.JButton();
        button13 = new javax.swing.JButton();
        button14 = new javax.swing.JButton();
        button15 = new javax.swing.JButton();
        button16 = new javax.swing.JButton();
        button17 = new javax.swing.JButton();
        button18 = new javax.swing.JButton();
        button19 = new javax.swing.JButton();
        button20 = new javax.swing.JButton();
        button21 = new javax.swing.JButton();
        button22 = new javax.swing.JButton();
        button23 = new javax.swing.JButton();
        button24 = new javax.swing.JButton();
        checkBox01 = new javax.swing.JCheckBox();
        checkBox02 = new javax.swing.JCheckBox();
        checkBox03 = new javax.swing.JCheckBox();
        checkBox04 = new javax.swing.JCheckBox();
        checkBox05 = new javax.swing.JCheckBox();
        checkBox06 = new javax.swing.JCheckBox();
        checkBox07 = new javax.swing.JCheckBox();
        checkBox08 = new javax.swing.JCheckBox();
        checkBox09 = new javax.swing.JCheckBox();
        checkBox10 = new javax.swing.JCheckBox();
        checkBox11 = new javax.swing.JCheckBox();
        checkBox12 = new javax.swing.JCheckBox();
        checkBox13 = new javax.swing.JCheckBox();
        checkBox14 = new javax.swing.JCheckBox();
        checkBox15 = new javax.swing.JCheckBox();
        checkBox16 = new javax.swing.JCheckBox();
        checkBox17 = new javax.swing.JCheckBox();
        checkBox18 = new javax.swing.JCheckBox();
        checkBox19 = new javax.swing.JCheckBox();
        checkBox20 = new javax.swing.JCheckBox();
        radioButton01 = new javax.swing.JRadioButton();
        radioButton02 = new javax.swing.JRadioButton();
        radioButton03 = new javax.swing.JRadioButton();
        radioButton04 = new javax.swing.JRadioButton();
        radioButton05 = new javax.swing.JRadioButton();
        radioButton06 = new javax.swing.JRadioButton();
        radioButton07 = new javax.swing.JRadioButton();
        radioButton08 = new javax.swing.JRadioButton();
        radioButton09 = new javax.swing.JRadioButton();
        radioButton10 = new javax.swing.JRadioButton();
        radioButton11 = new javax.swing.JRadioButton();
        radioButton12 = new javax.swing.JRadioButton();
        radioButton13 = new javax.swing.JRadioButton();
        radioButton14 = new javax.swing.JRadioButton();
        radioButton15 = new javax.swing.JRadioButton();
        radioButton16 = new javax.swing.JRadioButton();
        radioButton17 = new javax.swing.JRadioButton();
        radioButton18 = new javax.swing.JRadioButton();
        radioButton19 = new javax.swing.JRadioButton();
        radioButton20 = new javax.swing.JRadioButton();
        chartOptionPanel = new javax.swing.JPanel();
        jPanel43 = new javax.swing.JPanel();
        cbAutoAdjustY = new javax.swing.JCheckBox();
        jPanel45 = new javax.swing.JPanel();
        cbZero = new javax.swing.JCheckBox();
        cbRemark = new javax.swing.JCheckBox();
        jPanel46 = new javax.swing.JPanel();
        showAlarmRB = new javax.swing.JCheckBox();
        btnZoomIn = new javax.swing.JButton();
        btnZoomOut = new javax.swing.JButton();
        chartPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        deviceTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        stationList = new javax.swing.JList(stationListModel);
        panel01 = new javax.swing.JPanel();
        panel02 = new javax.swing.JPanel();
        panel03 = new javax.swing.JPanel();
        panel04 = new javax.swing.JPanel();
        panel05 = new javax.swing.JPanel();
        panel06 = new javax.swing.JPanel();
        panel07 = new javax.swing.JPanel();
        panel08 = new javax.swing.JPanel();
        panel09 = new javax.swing.JPanel();
        panel10 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        timeLabel.setFont(new java.awt.Font("Arial", 1, 12)); 
        timeLabel.setText("2016/06/04 21:59:03");
        add(timeLabel);
        timeLabel.setBounds(20, 320, 120, 15);

        button03.setFont(button03.getFont());
        button03.setText("button 03");
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("ci/Bundle"); 
        button03.setActionCommand(bundle.getString("CrInstrument.button03.actionCommand")); 
        button03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button03ActionPerformed(evt);
            }
        });
        add(button03);
        button03.setBounds(20, 280, 120, 40);

        button04.setFont(button04.getFont());
        button04.setText("button 04");
        button04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button04ActionPerformed(evt);
            }
        });
        add(button04);
        button04.setBounds(20, 280, 120, 40);

        button05.setFont(button05.getFont());
        button05.setText("button 05");
        button05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button05ActionPerformed(evt);
            }
        });
        add(button05);
        button05.setBounds(20, 280, 120, 40);

        button06.setFont(button06.getFont());
        button06.setText("button 06");
        button06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button06ActionPerformed(evt);
            }
        });
        add(button06);
        button06.setBounds(20, 280, 120, 40);

        button07.setFont(button07.getFont());
        button07.setText("button 07");
        button07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button07ActionPerformed(evt);
            }
        });
        add(button07);
        button07.setBounds(20, 280, 120, 40);

        button08.setFont(button08.getFont());
        button08.setText("button 08");
        button08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button08ActionPerformed(evt);
            }
        });
        add(button08);
        button08.setBounds(20, 280, 120, 40);

        button09.setFont(button09.getFont());
        button09.setText("button 09");
        button09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button09ActionPerformed(evt);
            }
        });
        add(button09);
        button09.setBounds(20, 280, 120, 40);

        button10.setFont(button10.getFont());
        button10.setText("button 10");
        button10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button10ActionPerformed(evt);
            }
        });
        add(button10);
        button10.setBounds(20, 280, 120, 40);

        btnStart.setFont(btnStart.getFont().deriveFont(btnStart.getFont().getStyle() | java.awt.Font.BOLD));
        btnStart.setText(bundle.getString("CrInstrument.btnStart.text")); 
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        add(btnStart);
        btnStart.setBounds(20, 460, 120, 40);

        button02.setFont(button02.getFont().deriveFont(button02.getFont().getStyle() | java.awt.Font.BOLD));
        button02.setText("button 02");
        button02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button02ActionPerformed(evt);
            }
        });
        add(button02);
        button02.setBounds(20, 410, 120, 40);

        btnConnect.setFont(btnConnect.getFont().deriveFont(btnConnect.getFont().getStyle() | java.awt.Font.BOLD));
        btnConnect.setText(bundle.getString("CrInstrument.btnConnect.text")); 
        btnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectActionPerformed(evt);
            }
        });
        add(btnConnect);
        btnConnect.setBounds(20, 360, 120, 40);

        statusLabel.setFont(new java.awt.Font("Arial", 1, 12)); 
        statusLabel.setText(bundle.getString("CrInstrument.statusLabel.text")); 
        add(statusLabel);
        statusLabel.setBounds(30, 520, 130, 20);

        javax.swing.GroupLayout lightPanelLayout = new javax.swing.GroupLayout(lightPanel);
        lightPanel.setLayout(lightPanelLayout);
        lightPanelLayout.setHorizontalGroup(
            lightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        lightPanelLayout.setVerticalGroup(
            lightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        add(lightPanel);
        lightPanel.setBounds(30, 550, 120, 50);

        textLabel01.setFont(textLabel01.getFont());
        textLabel01.setText("jLabel1");
        add(textLabel01);
        textLabel01.setBounds(20, 200, 110, 15);

        add(comboBox01);
        comboBox01.setBounds(20, 220, 100, 21);

        textField01.setText("jTextField1");
        add(textField01);
        textField01.setBounds(20, 250, 90, 21);

        textLabel02.setFont(textLabel02.getFont());
        textLabel02.setText("jLabel1");
        add(textLabel02);
        textLabel02.setBounds(20, 200, 110, 15);

        textLabel03.setFont(textLabel03.getFont());
        textLabel03.setText("jLabel1");
        add(textLabel03);
        textLabel03.setBounds(20, 200, 110, 15);

        textLabel04.setFont(textLabel04.getFont());
        textLabel04.setText("jLabel1");
        add(textLabel04);
        textLabel04.setBounds(20, 200, 110, 15);

        textLabel05.setFont(textLabel05.getFont());
        textLabel05.setText("jLabel1");
        add(textLabel05);
        textLabel05.setBounds(20, 200, 110, 15);

        textLabel06.setFont(textLabel06.getFont());
        textLabel06.setText("jLabel1");
        add(textLabel06);
        textLabel06.setBounds(20, 200, 110, 15);

        textLabel07.setFont(textLabel07.getFont());
        textLabel07.setText("jLabel1");
        add(textLabel07);
        textLabel07.setBounds(20, 200, 110, 15);

        textLabel08.setFont(textLabel08.getFont());
        textLabel08.setText("jLabel1");
        add(textLabel08);
        textLabel08.setBounds(20, 200, 110, 15);

        textLabel09.setFont(textLabel09.getFont());
        textLabel09.setText("jLabel1");
        add(textLabel09);
        textLabel09.setBounds(20, 200, 110, 15);

        textLabel10.setFont(textLabel10.getFont());
        textLabel10.setText("jLabel1");
        add(textLabel10);
        textLabel10.setBounds(20, 200, 110, 15);

        textLabel11.setFont(textLabel11.getFont());
        textLabel11.setText("jLabel1");
        add(textLabel11);
        textLabel11.setBounds(20, 200, 110, 15);

        textLabel12.setFont(textLabel12.getFont());
        textLabel12.setText("jLabel1");
        add(textLabel12);
        textLabel12.setBounds(20, 200, 110, 15);

        textLabel13.setFont(textLabel13.getFont());
        textLabel13.setText("jLabel1");
        add(textLabel13);
        textLabel13.setBounds(20, 200, 110, 15);

        textLabel14.setFont(textLabel14.getFont());
        textLabel14.setText("jLabel1");
        add(textLabel14);
        textLabel14.setBounds(20, 200, 110, 15);

        textLabel15.setFont(textLabel15.getFont());
        textLabel15.setText("jLabel1");
        add(textLabel15);
        textLabel15.setBounds(20, 200, 110, 15);

        textLabel16.setFont(textLabel16.getFont());
        textLabel16.setText("jLabel1");
        add(textLabel16);
        textLabel16.setBounds(20, 200, 110, 15);

        textLabel17.setFont(textLabel17.getFont());
        textLabel17.setText("jLabel1");
        add(textLabel17);
        textLabel17.setBounds(20, 200, 110, 15);

        textLabel18.setFont(textLabel18.getFont());
        textLabel18.setText("jLabel1");
        add(textLabel18);
        textLabel18.setBounds(20, 200, 110, 15);

        textLabel19.setFont(textLabel19.getFont());
        textLabel19.setText("jLabel1");
        add(textLabel19);
        textLabel19.setBounds(20, 200, 110, 15);

        textLabel20.setFont(textLabel20.getFont());
        textLabel20.setText("jLabel1");
        add(textLabel20);
        textLabel20.setBounds(20, 200, 110, 15);

        textLabel21.setFont(textLabel21.getFont());
        textLabel21.setText("jLabel1");
        add(textLabel21);
        textLabel21.setBounds(20, 200, 110, 15);

        textLabel22.setFont(textLabel22.getFont());
        textLabel22.setText("jLabel1");
        add(textLabel22);
        textLabel22.setBounds(20, 200, 110, 15);

        textLabel23.setFont(textLabel23.getFont());
        textLabel23.setText("jLabel1");
        add(textLabel23);
        textLabel23.setBounds(20, 200, 110, 15);

        textLabel24.setFont(textLabel24.getFont());
        textLabel24.setText("jLabel1");
        add(textLabel24);
        textLabel24.setBounds(20, 200, 110, 15);

        textLabel25.setFont(textLabel25.getFont());
        textLabel25.setText("jLabel1");
        add(textLabel25);
        textLabel25.setBounds(20, 200, 110, 15);

        textLabel26.setFont(textLabel26.getFont());
        textLabel26.setText("jLabel1");
        add(textLabel26);
        textLabel26.setBounds(20, 200, 110, 15);

        textLabel27.setFont(textLabel27.getFont());
        textLabel27.setText("jLabel1");
        add(textLabel27);
        textLabel27.setBounds(20, 200, 110, 15);

        textLabel28.setFont(textLabel28.getFont());
        textLabel28.setText("jLabel1");
        add(textLabel28);
        textLabel28.setBounds(20, 200, 110, 15);

        textLabel29.setFont(textLabel29.getFont());
        textLabel29.setText("jLabel1");
        add(textLabel29);
        textLabel29.setBounds(20, 200, 110, 15);

        textLabel30.setFont(textLabel30.getFont());
        textLabel30.setText("jLabel1");
        add(textLabel30);
        textLabel30.setBounds(20, 200, 110, 15);

        add(comboBox02);
        comboBox02.setBounds(20, 220, 100, 21);

        add(comboBox03);
        comboBox03.setBounds(20, 220, 100, 21);

        add(comboBox04);
        comboBox04.setBounds(20, 220, 100, 21);

        add(comboBox05);
        comboBox05.setBounds(20, 220, 100, 21);

        add(comboBox06);
        comboBox06.setBounds(20, 220, 100, 21);

        add(comboBox07);
        comboBox07.setBounds(20, 220, 100, 21);

        add(comboBox08);
        comboBox08.setBounds(20, 220, 100, 21);

        add(comboBox09);
        comboBox09.setBounds(20, 220, 100, 21);

        add(comboBox10);
        comboBox10.setBounds(20, 220, 100, 21);

        add(comboBox11);
        comboBox11.setBounds(20, 220, 100, 21);

        add(comboBox12);
        comboBox12.setBounds(20, 220, 100, 21);

        add(comboBox13);
        comboBox13.setBounds(20, 220, 100, 21);

        add(comboBox14);
        comboBox14.setBounds(20, 220, 100, 21);

        add(comboBox15);
        comboBox15.setBounds(20, 220, 100, 21);

        add(comboBox16);
        comboBox16.setBounds(20, 220, 100, 21);

        add(comboBox17);
        comboBox17.setBounds(20, 220, 100, 21);

        add(comboBox18);
        comboBox18.setBounds(20, 220, 100, 21);

        add(comboBox19);
        comboBox19.setBounds(20, 220, 100, 21);

        add(comboBox20);
        comboBox20.setBounds(20, 220, 100, 21);

        textField02.setText("jTextField1");
        add(textField02);
        textField02.setBounds(20, 250, 90, 21);

        textField03.setText("jTextField1");
        add(textField03);
        textField03.setBounds(20, 250, 90, 21);

        textField04.setText("jTextField1");
        add(textField04);
        textField04.setBounds(20, 250, 90, 21);

        textField05.setText("jTextField1");
        add(textField05);
        textField05.setBounds(20, 250, 90, 21);

        textField06.setText("jTextField1");
        add(textField06);
        textField06.setBounds(20, 250, 90, 21);

        textField07.setText("jTextField1");
        add(textField07);
        textField07.setBounds(20, 250, 90, 21);

        textField08.setText("jTextField1");
        add(textField08);
        textField08.setBounds(20, 250, 90, 21);

        textField09.setText("jTextField1");
        add(textField09);
        textField09.setBounds(20, 250, 90, 21);

        textField10.setText("jTextField1");
        add(textField10);
        textField10.setBounds(20, 250, 90, 21);

        textField11.setText("jTextField1");
        add(textField11);
        textField11.setBounds(20, 250, 90, 21);

        textField12.setText("jTextField1");
        add(textField12);
        textField12.setBounds(20, 250, 90, 21);

        textField13.setText("jTextField1");
        add(textField13);
        textField13.setBounds(20, 250, 90, 21);

        textField14.setText("jTextField1");
        add(textField14);
        textField14.setBounds(20, 250, 90, 21);

        textField15.setText("jTextField1");
        add(textField15);
        textField15.setBounds(20, 250, 90, 21);

        textField16.setText("jTextField1");
        add(textField16);
        textField16.setBounds(20, 250, 90, 21);

        textField17.setText("jTextField1");
        add(textField17);
        textField17.setBounds(20, 250, 90, 21);

        textField18.setText("jTextField1");
        add(textField18);
        textField18.setBounds(20, 250, 90, 21);

        textField19.setText("jTextField1");
        add(textField19);
        textField19.setBounds(20, 250, 90, 21);

        textField20.setText("jTextField1");
        add(textField20);
        textField20.setBounds(20, 250, 90, 21);

        textField21.setText("jTextField1");
        add(textField21);
        textField21.setBounds(20, 250, 90, 21);

        textField22.setText("jTextField1");
        add(textField22);
        textField22.setBounds(20, 250, 90, 21);

        textField23.setText("jTextField1");
        add(textField23);
        textField23.setBounds(20, 250, 90, 21);

        textField24.setText("jTextField1");
        add(textField24);
        textField24.setBounds(20, 250, 90, 21);

        textField25.setText("jTextField1");
        add(textField25);
        textField25.setBounds(20, 250, 90, 21);

        textField26.setText("jTextField1");
        add(textField26);
        textField26.setBounds(20, 250, 90, 21);

        textField27.setText("jTextField1");
        add(textField27);
        textField27.setBounds(20, 250, 90, 21);

        textField28.setText("jTextField1");
        add(textField28);
        textField28.setBounds(20, 250, 90, 21);

        textField29.setText("jTextField1");
        add(textField29);
        textField29.setBounds(20, 250, 90, 21);

        textField30.setText("jTextField1");
        add(textField30);
        textField30.setBounds(20, 250, 90, 21);

        button25.setFont(button25.getFont());
        button25.setText("button 25");
        button25.setActionCommand(bundle.getString("CrInstrument.button03.actionCommand")); 
        button25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button25ActionPerformed(evt);
            }
        });
        add(button25);
        button25.setBounds(20, 280, 120, 40);

        button26.setFont(button26.getFont());
        button26.setText("button 26");
        button26.setActionCommand(bundle.getString("CrInstrument.button03.actionCommand")); 
        button26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button26ActionPerformed(evt);
            }
        });
        add(button26);
        button26.setBounds(20, 280, 120, 40);

        button27.setFont(button27.getFont());
        button27.setText("button 27");
        button27.setActionCommand(bundle.getString("CrInstrument.button03.actionCommand")); 
        button27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button27ActionPerformed(evt);
            }
        });
        add(button27);
        button27.setBounds(20, 280, 120, 40);

        button28.setFont(button28.getFont());
        button28.setText("button 28");
        button28.setActionCommand(bundle.getString("CrInstrument.button03.actionCommand")); 
        button28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button28ActionPerformed(evt);
            }
        });
        add(button28);
        button28.setBounds(20, 280, 120, 40);

        button29.setFont(button29.getFont());
        button29.setText("button 29");
        button29.setActionCommand(bundle.getString("CrInstrument.button03.actionCommand")); 
        button29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button29ActionPerformed(evt);
            }
        });
        add(button29);
        button29.setBounds(20, 280, 120, 40);

        button30.setFont(button30.getFont());
        button30.setText("button 30");
        button30.setActionCommand(bundle.getString("CrInstrument.button03.actionCommand")); 
        button30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button30ActionPerformed(evt);
            }
        });
        add(button30);
        button30.setBounds(20, 280, 120, 40);

        button11.setFont(button11.getFont());
        button11.setText("button 11");
        button11.setActionCommand(bundle.getString("CrInstrument.button03.actionCommand")); 
        button11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button11ActionPerformed(evt);
            }
        });
        add(button11);
        button11.setBounds(20, 280, 120, 40);

        button12.setFont(button12.getFont());
        button12.setText("button 12");
        button12.setActionCommand(bundle.getString("CrInstrument.button03.actionCommand")); 
        button12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button12ActionPerformed(evt);
            }
        });
        add(button12);
        button12.setBounds(20, 280, 120, 40);

        button13.setFont(button13.getFont());
        button13.setText("button 13");
        button13.setActionCommand(bundle.getString("CrInstrument.button03.actionCommand")); 
        button13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button13ActionPerformed(evt);
            }
        });
        add(button13);
        button13.setBounds(20, 280, 120, 40);

        button14.setFont(button14.getFont());
        button14.setText("button 14");
        button14.setActionCommand(bundle.getString("CrInstrument.button03.actionCommand")); 
        button14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button14ActionPerformed(evt);
            }
        });
        add(button14);
        button14.setBounds(20, 280, 120, 40);

        button15.setFont(button15.getFont());
        button15.setText("button 15");
        button15.setActionCommand(bundle.getString("CrInstrument.button03.actionCommand")); 
        button15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button15ActionPerformed(evt);
            }
        });
        add(button15);
        button15.setBounds(20, 280, 120, 40);

        button16.setFont(button16.getFont());
        button16.setText("button 16");
        button16.setActionCommand(bundle.getString("CrInstrument.button03.actionCommand")); 
        button16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button16ActionPerformed(evt);
            }
        });
        add(button16);
        button16.setBounds(20, 280, 120, 40);

        button17.setFont(button17.getFont());
        button17.setText("button 17");
        button17.setActionCommand(bundle.getString("CrInstrument.button03.actionCommand")); 
        button17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button17ActionPerformed(evt);
            }
        });
        add(button17);
        button17.setBounds(20, 280, 120, 40);

        button18.setFont(button18.getFont());
        button18.setText("button 18");
        button18.setActionCommand(bundle.getString("CrInstrument.button03.actionCommand")); 
        button18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button18ActionPerformed(evt);
            }
        });
        add(button18);
        button18.setBounds(20, 280, 120, 40);

        button19.setFont(button19.getFont());
        button19.setText("button 19");
        button19.setActionCommand(bundle.getString("CrInstrument.button03.actionCommand")); 
        button19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button19ActionPerformed(evt);
            }
        });
        add(button19);
        button19.setBounds(20, 280, 120, 40);

        button20.setFont(button20.getFont());
        button20.setText("button 20");
        button20.setActionCommand(bundle.getString("CrInstrument.button03.actionCommand")); 
        button20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button20ActionPerformed(evt);
            }
        });
        add(button20);
        button20.setBounds(20, 280, 120, 40);

        button21.setFont(button21.getFont());
        button21.setText("button 21");
        button21.setActionCommand(bundle.getString("CrInstrument.button03.actionCommand")); 
        button21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button21ActionPerformed(evt);
            }
        });
        add(button21);
        button21.setBounds(20, 280, 120, 40);

        button22.setFont(button22.getFont());
        button22.setText("button 22");
        button22.setActionCommand(bundle.getString("CrInstrument.button03.actionCommand")); 
        button22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button22ActionPerformed(evt);
            }
        });
        add(button22);
        button22.setBounds(20, 280, 120, 40);

        button23.setFont(button23.getFont());
        button23.setText("button 23");
        button23.setActionCommand(bundle.getString("CrInstrument.button03.actionCommand")); 
        button23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button23ActionPerformed(evt);
            }
        });
        add(button23);
        button23.setBounds(20, 280, 120, 40);

        button24.setFont(button24.getFont());
        button24.setText("button 24");
        button24.setActionCommand(bundle.getString("CrInstrument.button03.actionCommand")); 
        button24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button24ActionPerformed(evt);
            }
        });
        add(button24);
        button24.setBounds(20, 280, 120, 40);

        checkBox01.setFont(checkBox01.getFont());
        checkBox01.setText("checkbox 01");
        add(checkBox01);
        checkBox01.setBounds(180, 320, 85, 23);

        checkBox02.setFont(checkBox02.getFont());
        checkBox02.setText("checkbox 02");
        add(checkBox02);
        checkBox02.setBounds(180, 320, 85, 23);

        checkBox03.setFont(checkBox03.getFont());
        checkBox03.setText("checkbox 03");
        add(checkBox03);
        checkBox03.setBounds(180, 320, 85, 23);

        checkBox04.setFont(checkBox04.getFont());
        checkBox04.setText("checkbox 04");
        add(checkBox04);
        checkBox04.setBounds(180, 320, 85, 23);

        checkBox05.setFont(checkBox05.getFont());
        checkBox05.setText("checkbox 05");
        add(checkBox05);
        checkBox05.setBounds(180, 320, 85, 23);

        checkBox06.setFont(checkBox06.getFont());
        checkBox06.setText("checkbox 06");
        add(checkBox06);
        checkBox06.setBounds(180, 320, 85, 23);

        checkBox07.setFont(checkBox07.getFont());
        checkBox07.setText("checkbox 07");
        add(checkBox07);
        checkBox07.setBounds(180, 320, 85, 23);

        checkBox08.setFont(checkBox08.getFont());
        checkBox08.setText("checkbox 08");
        add(checkBox08);
        checkBox08.setBounds(180, 320, 85, 23);

        checkBox09.setFont(checkBox09.getFont());
        checkBox09.setText("checkbox 09");
        add(checkBox09);
        checkBox09.setBounds(180, 320, 85, 23);

        checkBox10.setFont(checkBox10.getFont());
        checkBox10.setText("checkbox 10");
        add(checkBox10);
        checkBox10.setBounds(180, 320, 85, 23);

        checkBox11.setFont(checkBox11.getFont());
        checkBox11.setText("checkbox 11");
        add(checkBox11);
        checkBox11.setBounds(180, 320, 85, 23);

        checkBox12.setFont(checkBox12.getFont());
        checkBox12.setText("checkbox 12");
        add(checkBox12);
        checkBox12.setBounds(180, 320, 85, 23);

        checkBox13.setFont(checkBox13.getFont());
        checkBox13.setText("checkbox 13");
        add(checkBox13);
        checkBox13.setBounds(180, 320, 85, 23);

        checkBox14.setFont(checkBox14.getFont());
        checkBox14.setText("checkbox 14");
        add(checkBox14);
        checkBox14.setBounds(180, 320, 85, 23);

        checkBox15.setFont(checkBox15.getFont());
        checkBox15.setText("checkbox 15");
        add(checkBox15);
        checkBox15.setBounds(180, 320, 85, 23);

        checkBox16.setFont(checkBox16.getFont());
        checkBox16.setText("checkbox 16");
        add(checkBox16);
        checkBox16.setBounds(180, 320, 85, 23);

        checkBox17.setFont(checkBox17.getFont());
        checkBox17.setText("checkbox 17");
        add(checkBox17);
        checkBox17.setBounds(180, 320, 85, 23);

        checkBox18.setFont(checkBox18.getFont());
        checkBox18.setText("checkbox 18");
        add(checkBox18);
        checkBox18.setBounds(180, 320, 85, 23);

        checkBox19.setFont(checkBox19.getFont());
        checkBox19.setText("checkbox 19");
        add(checkBox19);
        checkBox19.setBounds(180, 320, 85, 23);

        checkBox20.setFont(checkBox20.getFont());
        checkBox20.setText("checkbox 20");
        add(checkBox20);
        checkBox20.setBounds(180, 320, 85, 23);

        radioButton01.setFont(radioButton01.getFont());
        radioButton01.setText("radiobutton 01");
        add(radioButton01);
        radioButton01.setBounds(310, 320, 95, 23);

        radioButton02.setFont(radioButton02.getFont());
        radioButton02.setText("radiobutton 02");
        add(radioButton02);
        radioButton02.setBounds(310, 320, 95, 23);

        radioButton03.setFont(radioButton03.getFont());
        radioButton03.setText("radiobutton 03");
        add(radioButton03);
        radioButton03.setBounds(310, 320, 95, 23);

        radioButton04.setFont(radioButton04.getFont());
        radioButton04.setText("radiobutton 04");
        add(radioButton04);
        radioButton04.setBounds(310, 320, 95, 23);

        radioButton05.setFont(radioButton05.getFont());
        radioButton05.setText("radiobutton 05");
        add(radioButton05);
        radioButton05.setBounds(310, 320, 95, 23);

        radioButton06.setFont(radioButton06.getFont());
        radioButton06.setText("radiobutton 06");
        add(radioButton06);
        radioButton06.setBounds(310, 320, 95, 23);

        radioButton07.setFont(radioButton07.getFont());
        radioButton07.setText("radiobutton 07");
        add(radioButton07);
        radioButton07.setBounds(310, 320, 95, 23);

        radioButton08.setFont(radioButton08.getFont());
        radioButton08.setText("radiobutton 08");
        add(radioButton08);
        radioButton08.setBounds(310, 320, 95, 23);

        radioButton09.setFont(radioButton09.getFont());
        radioButton09.setText("radiobutton 09");
        add(radioButton09);
        radioButton09.setBounds(310, 320, 95, 23);

        radioButton10.setFont(radioButton10.getFont());
        radioButton10.setText("radiobutton 10");
        add(radioButton10);
        radioButton10.setBounds(310, 320, 95, 23);

        radioButton11.setFont(radioButton11.getFont());
        radioButton11.setText("radiobutton 11");
        add(radioButton11);
        radioButton11.setBounds(310, 320, 95, 23);

        radioButton12.setFont(radioButton12.getFont());
        radioButton12.setText("radiobutton 12");
        add(radioButton12);
        radioButton12.setBounds(310, 320, 95, 23);

        radioButton13.setFont(radioButton13.getFont());
        radioButton13.setText("radiobutton 13");
        add(radioButton13);
        radioButton13.setBounds(310, 320, 95, 23);

        radioButton14.setFont(radioButton14.getFont());
        radioButton14.setText("radiobutton 14");
        add(radioButton14);
        radioButton14.setBounds(310, 320, 95, 23);

        radioButton15.setFont(radioButton15.getFont());
        radioButton15.setText("radiobutton 15");
        add(radioButton15);
        radioButton15.setBounds(310, 320, 95, 23);

        radioButton16.setFont(radioButton16.getFont());
        radioButton16.setText("radiobutton 16");
        add(radioButton16);
        radioButton16.setBounds(310, 320, 95, 23);

        radioButton17.setFont(radioButton17.getFont());
        radioButton17.setText("radiobutton 17");
        add(radioButton17);
        radioButton17.setBounds(310, 320, 95, 23);

        radioButton18.setFont(radioButton18.getFont());
        radioButton18.setText("radiobutton 18");
        add(radioButton18);
        radioButton18.setBounds(310, 320, 95, 23);

        radioButton19.setFont(radioButton19.getFont());
        radioButton19.setText("radiobutton 19");
        add(radioButton19);
        radioButton19.setBounds(310, 320, 95, 23);

        radioButton20.setFont(radioButton20.getFont());
        radioButton20.setText("radiobutton 20");
        add(radioButton20);
        radioButton20.setBounds(310, 320, 95, 23);

        chartOptionPanel.setBackground(new java.awt.Color(255, 255, 255));
        chartOptionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true), bundle.getString("CrInstrument.chartOptionPanel.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("·s²Ó©úÅé", 0, 12), new java.awt.Color(51, 51, 51))); 
        chartOptionPanel.setFont(chartOptionPanel.getFont());
        chartOptionPanel.setLayout(new java.awt.GridLayout(3, 1));

        jPanel43.setOpaque(false);

        cbAutoAdjustY.setFont(cbAutoAdjustY.getFont());
        cbAutoAdjustY.setText(bundle.getString("CrInstrument.cbAutoAdjustY.text")); 
        cbAutoAdjustY.setOpaque(false);
        cbAutoAdjustY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAutoAdjustYActionPerformed(evt);
            }
        });
        jPanel43.add(cbAutoAdjustY);

        chartOptionPanel.add(jPanel43);

        jPanel45.setOpaque(false);

        cbZero.setFont(cbZero.getFont());
        cbZero.setText(bundle.getString("CrInstrument.cbZero.text")); 
        cbZero.setOpaque(false);
        cbZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbZeroActionPerformed(evt);
            }
        });
        jPanel45.add(cbZero);

        cbRemark.setFont(cbRemark.getFont());
        cbRemark.setText(bundle.getString("CrInstrument.cbRemark.text")); 
        cbRemark.setOpaque(false);
        jPanel45.add(cbRemark);

        chartOptionPanel.add(jPanel45);

        jPanel46.setOpaque(false);

        showAlarmRB.setBackground(new java.awt.Color(255, 255, 255));
        showAlarmRB.setFont(showAlarmRB.getFont());
        showAlarmRB.setText(bundle.getString("CrInstrument.showAlarmRB.text")); 
        showAlarmRB.setOpaque(false);
        showAlarmRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAlarmRBActionPerformed(evt);
            }
        });
        jPanel46.add(showAlarmRB);

        btnZoomIn.setFont(btnZoomIn.getFont());
        btnZoomIn.setText(bundle.getString("CrInstrument.btnZoomIn.text")); 
        btnZoomIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZoomInActionPerformed(evt);
            }
        });
        jPanel46.add(btnZoomIn);

        btnZoomOut.setFont(btnZoomOut.getFont());
        btnZoomOut.setText(bundle.getString("CrInstrument.btnZoomOut.text")); 
        btnZoomOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZoomOutActionPerformed(evt);
            }
        });
        jPanel46.add(btnZoomOut);

        chartOptionPanel.add(jPanel46);

        add(chartOptionPanel);
        chartOptionPanel.setBounds(560, 480, 440, 130);

        chartPanel.setBackground(new java.awt.Color(255, 255, 255));
        chartPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), bundle.getString("CrInstrument.chartPanel.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP)); 
        chartPanel.setFont(chartPanel.getFont());
        chartPanel.setLayout(new java.awt.BorderLayout());
        add(chartPanel);
        chartPanel.setBounds(560, 10, 440, 460);

        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)), bundle.getString("CrInstrument.jScrollPane3.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP)); 
        jScrollPane3.setFont(jScrollPane3.getFont());

        deviceTable.setFont(deviceTable.getFont());
        deviceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Device Name", "Model", "SN", "Data Name", "Value", "Alert"
            }
        ));
        deviceTable.setGridColor(new java.awt.Color(153, 153, 153));
        deviceTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deviceTableMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                deviceTableMouseReleased(evt);
            }
        });
        jScrollPane3.setViewportView(deviceTable);

        add(jScrollPane3);
        jScrollPane3.setBounds(170, 10, 380, 300);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)), bundle.getString("CrInstrument.jScrollPane2.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP)); 
        jScrollPane2.setFont(jScrollPane2.getFont());

        stationList.setFont(stationList.getFont());
        stationList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                stationListMouseReleased(evt);
            }
        });
        stationList.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                stationListKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(stationList);

        add(jScrollPane2);
        jScrollPane2.setBounds(0, 10, 160, 180);

        panel01.setBackground(new java.awt.Color(204, 255, 255));
        panel01.setLayout(null);
        add(panel01);
        panel01.setBounds(180, 370, 110, 100);

        panel02.setBackground(new java.awt.Color(204, 255, 255));
        panel02.setLayout(null);
        add(panel02);
        panel02.setBounds(180, 370, 110, 100);

        panel03.setBackground(new java.awt.Color(204, 255, 255));
        panel03.setLayout(null);
        add(panel03);
        panel03.setBounds(180, 370, 110, 100);

        panel04.setBackground(new java.awt.Color(204, 255, 255));
        panel04.setLayout(null);
        add(panel04);
        panel04.setBounds(180, 370, 110, 100);

        panel05.setBackground(new java.awt.Color(204, 255, 255));
        panel05.setLayout(null);
        add(panel05);
        panel05.setBounds(180, 370, 110, 100);

        panel06.setBackground(new java.awt.Color(204, 255, 255));
        panel06.setLayout(null);
        add(panel06);
        panel06.setBounds(180, 370, 110, 100);

        panel07.setBackground(new java.awt.Color(204, 255, 255));
        panel07.setLayout(null);
        add(panel07);
        panel07.setBounds(180, 370, 110, 100);

        panel08.setBackground(new java.awt.Color(204, 255, 255));
        panel08.setLayout(null);
        add(panel08);
        panel08.setBounds(180, 370, 110, 100);

        panel09.setBackground(new java.awt.Color(204, 255, 255));
        panel09.setLayout(null);
        add(panel09);
        panel09.setBounds(180, 370, 110, 100);

        panel10.setBackground(new java.awt.Color(204, 255, 255));
        panel10.setLayout(null);
        add(panel10);
        panel10.setBounds(180, 370, 110, 100);
    }

    private void button03ActionPerformed(java.awt.event.ActionEvent evt) {
        instrument.eventThread.setStatus(instrument.wn.w.getGNS(1),"",27);
    }

    private void button04ActionPerformed(java.awt.event.ActionEvent evt) {
        instrument.eventThread.setStatus(instrument.wn.w.getGNS(1),"",28);
    }

    private void button05ActionPerformed(java.awt.event.ActionEvent evt) {
        instrument.eventThread.setStatus(instrument.wn.w.getGNS(1),"",29);
    }

    private void button06ActionPerformed(java.awt.event.ActionEvent evt) {
        instrument.eventThread.setStatus(instrument.wn.w.getGNS(1),"",30);
    }

    private void button07ActionPerformed(java.awt.event.ActionEvent evt) {
        instrument.eventThread.setStatus(instrument.wn.w.getGNS(1),"",31);
    }

    private void button08ActionPerformed(java.awt.event.ActionEvent evt) {
        instrument.eventThread.setStatus(instrument.wn.w.getGNS(1),"",32);
    }

    private void button09ActionPerformed(java.awt.event.ActionEvent evt) {
        instrument.eventThread.setStatus(instrument.wn.w.getGNS(1),"",33);
    }

    private void button10ActionPerformed(java.awt.event.ActionEvent evt) {
        instrument.eventThread.setStatus(instrument.wn.w.getGNS(1),"",34);
    }

    private void stationListMouseReleased(java.awt.event.MouseEvent evt) {
        String selectedItem = (String)stationList.getSelectedValue();

        instrument.showStation(selectedItem);
    }

    private void stationListKeyReleased(java.awt.event.KeyEvent evt) {
        if(evt.getKeyCode()==38 || evt.getKeyCode()==40 )  instrument.showStation((String)stationList.getSelectedValue());
    }

    private void deviceTableMouseClicked(java.awt.event.MouseEvent evt) {
        int row = deviceTable.getSelectedRow();
        int column = deviceTable.getSelectedColumn();
        String device = (String) deviceTable.getModel().getValueAt(row, 0);
        String model = (String) deviceTable.getModel().getValueAt(row, 1);
        String SN = (String) deviceTable.getModel().getValueAt(row, 2);
        String dataName = (String) deviceTable.getModel().getValueAt(row, 3);
        String id=device+","+model+","+SN+","+dataName;
        if (id != null && id.length() > 0) {
            instrument.currentTable2Row = row;
            instrument.currentSensorID = instrument.currentStation + "," + id;
            instrument.showSensorData(row);
            deviceTable.repaint();
            instrument.showCurve(instrument.currentSensorID);
        }
    }

    private void deviceTableMouseReleased(java.awt.event.MouseEvent evt) {

    }

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {
        instrument.pressStartBtn(1);
    }

    private void button02ActionPerformed(java.awt.event.ActionEvent evt) {
        instrument.eventThread.setStatus(instrument.wn.w.getGNS(1),"",26);
    }

    private void btnConnectActionPerformed(java.awt.event.ActionEvent evt) {
        instrument.connect();
    }

    private void cbAutoAdjustYActionPerformed(java.awt.event.ActionEvent evt) {
        instrument.dataUpdated = true;
    }

    private void cbZeroActionPerformed(java.awt.event.ActionEvent evt) {
        instrument.dataUpdated = true;
    }

    private void showAlarmRBActionPerformed(java.awt.event.ActionEvent evt) {
        instrument.dataUpdated = true;
    }

    private void btnZoomInActionPerformed(java.awt.event.ActionEvent evt) {
        if (instrument.roomIndex > 0) {
            instrument.roomIndex--;
            instrument.dataUpdated = true;
        }
    }

    private void btnZoomOutActionPerformed(java.awt.event.ActionEvent evt) {
        if (instrument.roomIndex < (instrument.roomValues.length - 1)) {
            instrument.roomIndex++;
            instrument.dataUpdated = true;
        } 
    }

    private void button25ActionPerformed(java.awt.event.ActionEvent evt) {
        instrument.eventThread.setStatus(instrument.wn.w.getGNS(1),"",66);
    }

    private void button26ActionPerformed(java.awt.event.ActionEvent evt) {
        instrument.eventThread.setStatus(instrument.wn.w.getGNS(1),"",67);
    }

    private void button27ActionPerformed(java.awt.event.ActionEvent evt) {
        instrument.eventThread.setStatus(instrument.wn.w.getGNS(1),"",68);
    }

    private void button28ActionPerformed(java.awt.event.ActionEvent evt) {
        instrument.eventThread.setStatus(instrument.wn.w.getGNS(1),"",69);
    }

    private void button29ActionPerformed(java.awt.event.ActionEvent evt) {
        instrument.eventThread.setStatus(instrument.wn.w.getGNS(1),"",70);
    }

    private void button30ActionPerformed(java.awt.event.ActionEvent evt) {
        instrument.eventThread.setStatus(instrument.wn.w.getGNS(1),"",71);
    }

    private void button11ActionPerformed(java.awt.event.ActionEvent evt) {
        instrument.eventThread.setStatus(instrument.wn.w.getGNS(1),"",52);
    }

    private void button12ActionPerformed(java.awt.event.ActionEvent evt) {
        instrument.eventThread.setStatus(instrument.wn.w.getGNS(1),"",53);
    }

    private void button13ActionPerformed(java.awt.event.ActionEvent evt) {
        instrument.eventThread.setStatus(instrument.wn.w.getGNS(1),"",54);
    }

    private void button14ActionPerformed(java.awt.event.ActionEvent evt) {
        instrument.eventThread.setStatus(instrument.wn.w.getGNS(1),"",55);
    }

    private void button15ActionPerformed(java.awt.event.ActionEvent evt) {
        instrument.eventThread.setStatus(instrument.wn.w.getGNS(1),"",56);
    }

    private void button16ActionPerformed(java.awt.event.ActionEvent evt) {
        instrument.eventThread.setStatus(instrument.wn.w.getGNS(1),"",57);
    }

    private void button17ActionPerformed(java.awt.event.ActionEvent evt) {
        instrument.eventThread.setStatus(instrument.wn.w.getGNS(1),"",58);
    }

    private void button18ActionPerformed(java.awt.event.ActionEvent evt) {
        instrument.eventThread.setStatus(instrument.wn.w.getGNS(1),"",59);
    }

    private void button19ActionPerformed(java.awt.event.ActionEvent evt) {
        instrument.eventThread.setStatus(instrument.wn.w.getGNS(1),"",60);
    }

    private void button20ActionPerformed(java.awt.event.ActionEvent evt) {
        instrument.eventThread.setStatus(instrument.wn.w.getGNS(1),"",61);
    }

    private void button21ActionPerformed(java.awt.event.ActionEvent evt) {
        instrument.eventThread.setStatus(instrument.wn.w.getGNS(1),"",62);
    }

    private void button22ActionPerformed(java.awt.event.ActionEvent evt) {
        instrument.eventThread.setStatus(instrument.wn.w.getGNS(1),"",63);
    }

    private void button23ActionPerformed(java.awt.event.ActionEvent evt) {
        instrument.eventThread.setStatus(instrument.wn.w.getGNS(1),"",64);
    }

    private void button24ActionPerformed(java.awt.event.ActionEvent evt) {
        instrument.eventThread.setStatus(instrument.wn.w.getGNS(1),"",65);
    }

    public javax.swing.JButton btnConnect;
    public javax.swing.JButton btnStart;
    public javax.swing.JButton btnZoomIn;
    public javax.swing.JButton btnZoomOut;
    public javax.swing.JButton button02;
    public javax.swing.JButton button03;
    public javax.swing.JButton button04;
    public javax.swing.JButton button05;
    public javax.swing.JButton button06;
    public javax.swing.JButton button07;
    public javax.swing.JButton button08;
    public javax.swing.JButton button09;
    public javax.swing.JButton button10;
    public javax.swing.JButton button11;
    public javax.swing.JButton button12;
    public javax.swing.JButton button13;
    public javax.swing.JButton button14;
    public javax.swing.JButton button15;
    public javax.swing.JButton button16;
    public javax.swing.JButton button17;
    public javax.swing.JButton button18;
    public javax.swing.JButton button19;
    public javax.swing.JButton button20;
    public javax.swing.JButton button21;
    public javax.swing.JButton button22;
    public javax.swing.JButton button23;
    public javax.swing.JButton button24;
    public javax.swing.JButton button25;
    public javax.swing.JButton button26;
    public javax.swing.JButton button27;
    public javax.swing.JButton button28;
    public javax.swing.JButton button29;
    public javax.swing.JButton button30;
    public javax.swing.ButtonGroup buttonGroup01;
    public javax.swing.ButtonGroup buttonGroup02;
    public javax.swing.ButtonGroup buttonGroup03;
    public javax.swing.ButtonGroup buttonGroup04;
    public javax.swing.ButtonGroup buttonGroup05;
    public javax.swing.ButtonGroup buttonGroup06;
    public javax.swing.ButtonGroup buttonGroup07;
    public javax.swing.ButtonGroup buttonGroup08;
    public javax.swing.ButtonGroup buttonGroup09;
    public javax.swing.ButtonGroup buttonGroup10;
    public javax.swing.JCheckBox cbAutoAdjustY;
    public javax.swing.JCheckBox cbRemark;
    public javax.swing.JCheckBox cbZero;
    public javax.swing.JPanel chartOptionPanel;
    public javax.swing.JPanel chartPanel;
    public javax.swing.JCheckBox checkBox01;
    public javax.swing.JCheckBox checkBox02;
    public javax.swing.JCheckBox checkBox03;
    public javax.swing.JCheckBox checkBox04;
    public javax.swing.JCheckBox checkBox05;
    public javax.swing.JCheckBox checkBox06;
    public javax.swing.JCheckBox checkBox07;
    public javax.swing.JCheckBox checkBox08;
    public javax.swing.JCheckBox checkBox09;
    public javax.swing.JCheckBox checkBox10;
    public javax.swing.JCheckBox checkBox11;
    public javax.swing.JCheckBox checkBox12;
    public javax.swing.JCheckBox checkBox13;
    public javax.swing.JCheckBox checkBox14;
    public javax.swing.JCheckBox checkBox15;
    public javax.swing.JCheckBox checkBox16;
    public javax.swing.JCheckBox checkBox17;
    public javax.swing.JCheckBox checkBox18;
    public javax.swing.JCheckBox checkBox19;
    public javax.swing.JCheckBox checkBox20;
    public javax.swing.JComboBox comboBox01;
    public javax.swing.JComboBox comboBox02;
    public javax.swing.JComboBox comboBox03;
    public javax.swing.JComboBox comboBox04;
    public javax.swing.JComboBox comboBox05;
    public javax.swing.JComboBox comboBox06;
    public javax.swing.JComboBox comboBox07;
    public javax.swing.JComboBox comboBox08;
    public javax.swing.JComboBox comboBox09;
    public javax.swing.JComboBox comboBox10;
    public javax.swing.JComboBox comboBox11;
    public javax.swing.JComboBox comboBox12;
    public javax.swing.JComboBox comboBox13;
    public javax.swing.JComboBox comboBox14;
    public javax.swing.JComboBox comboBox15;
    public javax.swing.JComboBox comboBox16;
    public javax.swing.JComboBox comboBox17;
    public javax.swing.JComboBox comboBox18;
    public javax.swing.JComboBox comboBox19;
    public javax.swing.JComboBox comboBox20;
    public javax.swing.JTable deviceTable;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollPane jScrollPane3;
    public ci.LightPanel lightPanel;
    public javax.swing.JPanel panel01;
    public javax.swing.JPanel panel02;
    public javax.swing.JPanel panel03;
    public javax.swing.JPanel panel04;
    public javax.swing.JPanel panel05;
    public javax.swing.JPanel panel06;
    public javax.swing.JPanel panel07;
    public javax.swing.JPanel panel08;
    public javax.swing.JPanel panel09;
    public javax.swing.JPanel panel10;
    public javax.swing.JRadioButton radioButton01;
    public javax.swing.JRadioButton radioButton02;
    public javax.swing.JRadioButton radioButton03;
    public javax.swing.JRadioButton radioButton04;
    public javax.swing.JRadioButton radioButton05;
    public javax.swing.JRadioButton radioButton06;
    public javax.swing.JRadioButton radioButton07;
    public javax.swing.JRadioButton radioButton08;
    public javax.swing.JRadioButton radioButton09;
    public javax.swing.JRadioButton radioButton10;
    public javax.swing.JRadioButton radioButton11;
    public javax.swing.JRadioButton radioButton12;
    public javax.swing.JRadioButton radioButton13;
    public javax.swing.JRadioButton radioButton14;
    public javax.swing.JRadioButton radioButton15;
    public javax.swing.JRadioButton radioButton16;
    public javax.swing.JRadioButton radioButton17;
    public javax.swing.JRadioButton radioButton18;
    public javax.swing.JRadioButton radioButton19;
    public javax.swing.JRadioButton radioButton20;
    public javax.swing.JCheckBox showAlarmRB;
    public javax.swing.JList stationList;
    public javax.swing.JLabel statusLabel;
    public javax.swing.JTextField textField01;
    public javax.swing.JTextField textField02;
    public javax.swing.JTextField textField03;
    public javax.swing.JTextField textField04;
    public javax.swing.JTextField textField05;
    public javax.swing.JTextField textField06;
    public javax.swing.JTextField textField07;
    public javax.swing.JTextField textField08;
    public javax.swing.JTextField textField09;
    public javax.swing.JTextField textField10;
    public javax.swing.JTextField textField11;
    public javax.swing.JTextField textField12;
    public javax.swing.JTextField textField13;
    public javax.swing.JTextField textField14;
    public javax.swing.JTextField textField15;
    public javax.swing.JTextField textField16;
    public javax.swing.JTextField textField17;
    public javax.swing.JTextField textField18;
    public javax.swing.JTextField textField19;
    public javax.swing.JTextField textField20;
    public javax.swing.JTextField textField21;
    public javax.swing.JTextField textField22;
    public javax.swing.JTextField textField23;
    public javax.swing.JTextField textField24;
    public javax.swing.JTextField textField25;
    public javax.swing.JTextField textField26;
    public javax.swing.JTextField textField27;
    public javax.swing.JTextField textField28;
    public javax.swing.JTextField textField29;
    public javax.swing.JTextField textField30;
    public javax.swing.JLabel textLabel01;
    public javax.swing.JLabel textLabel02;
    public javax.swing.JLabel textLabel03;
    public javax.swing.JLabel textLabel04;
    public javax.swing.JLabel textLabel05;
    public javax.swing.JLabel textLabel06;
    public javax.swing.JLabel textLabel07;
    public javax.swing.JLabel textLabel08;
    public javax.swing.JLabel textLabel09;
    public javax.swing.JLabel textLabel10;
    public javax.swing.JLabel textLabel11;
    public javax.swing.JLabel textLabel12;
    public javax.swing.JLabel textLabel13;
    public javax.swing.JLabel textLabel14;
    public javax.swing.JLabel textLabel15;
    public javax.swing.JLabel textLabel16;
    public javax.swing.JLabel textLabel17;
    public javax.swing.JLabel textLabel18;
    public javax.swing.JLabel textLabel19;
    public javax.swing.JLabel textLabel20;
    public javax.swing.JLabel textLabel21;
    public javax.swing.JLabel textLabel22;
    public javax.swing.JLabel textLabel23;
    public javax.swing.JLabel textLabel24;
    public javax.swing.JLabel textLabel25;
    public javax.swing.JLabel textLabel26;
    public javax.swing.JLabel textLabel27;
    public javax.swing.JLabel textLabel28;
    public javax.swing.JLabel textLabel29;
    public javax.swing.JLabel textLabel30;
    public javax.swing.JLabel timeLabel;

}