package ci;

import java.io.*;
import java.awt.*;
import java.util.ResourceBundle;
import javax.swing.ImageIcon;
public class CISocketportOptions extends javax.swing.JDialog {

  CrInstrument instrument;
    public ResourceBundle bundle2 = java.util.ResourceBundle.getBundle("ci/Bundle");
  public CISocketportOptions(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
    this.instrument=(CrInstrument)parent;
      int width=Toolkit.getDefaultToolkit().getScreenSize().width;
        int h=Toolkit.getDefaultToolkit().getScreenSize().height-20;

        int w2=600;
        int h2=540;

        setSize(w2,h2);

        setLocation((width-w2)/2,(h-h2)/2);

        Image iconImage=new ImageIcon(getClass().getClassLoader().getResource("crtc_logo_t.gif")).getImage();
        setIconImage(iconImage);
    init();
  }
  public void init(){
   String id=instrument.getItemId((String)instrument.nodeMgntPanel2.socketPortList.getSelectedValue()); 
   String itemname=instrument.wn.getItemName((String)instrument.nodeMgntPanel2.socketPortList.getSelectedValue());

   setTitle("Options for Socket port "+itemname);
   String conf[]=instrument.wn.w.csvLineToArray(instrument.nodeMgntPanel2.socketportConfig);
   if(conf.length > 1 && instrument.isNumeric(conf[1])) jTextField1.setText(conf[1]); else jTextField1.setText("1");
   if(conf.length > 4 && instrument.isNumeric(conf[4])) jTextField2.setText(conf[4]); else jTextField2.setText("60");
   if(conf.length > 5 && instrument.isNumeric(conf[5])){
     switch(Integer.parseInt(conf[5])){
       case 0:
         jRadioButton1.setSelected(true);
         break;
       case 1:
         jRadioButton2.setSelected(true);
         break;
       case 2:
         jRadioButton3.setSelected(true);
         if(conf.length > 6) jTextField3.setText(conf[6]); else jTextField3.setText("");
         break;
       case 3:
         jRadioButton4.setSelected(true);
         if(conf.length > 6) jTextField4.setText(conf[6]); else jTextField4.setText("");
         break;
       case 5:
         jRadioButton5.setSelected(true);
         if(conf.length > 6) jTextField5.setText(conf[6]); else jTextField5.setText("");
         break;
       case 7:
         jRadioButton6.setSelected(true);
         break;
     }
   } else jRadioButton2.setSelected(true);
   if(conf.length > 9)  jTextField6.setText(conf[9]); else jTextField6.setText("hi");
   this.setVisible(true);
  }
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")

    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getSize()+6f));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("ci/Bundle"); 
        jLabel1.setText(bundle.getString("CISocketportOptions.jLabel1.text")); 
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 10, 410, 30);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(jRadioButton1.getFont().deriveFont(jRadioButton1.getFont().getSize()+6f));
        jRadioButton1.setText(bundle.getString("CISocketportOptions.jRadioButton1.text")); 
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(30, 50, 440, 30);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("·s²Ó©úÅé", 0, 18)); 
        jRadioButton2.setSelected(true);
        jRadioButton2.setText(bundle.getString("CISocketportOptions.jRadioButton2.text")); 
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(30, 80, 350, 30);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(jRadioButton3.getFont().deriveFont(jRadioButton3.getFont().getSize()+6f));
        jRadioButton3.setText(bundle.getString("CISocketportOptions.jRadioButton3.text")); 
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(30, 170, 210, 31);

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(jRadioButton4.getFont().deriveFont(jRadioButton4.getFont().getSize()+6f));
        jRadioButton4.setText(bundle.getString("CISocketportOptions.jRadioButton4.text")); 
        getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(30, 200, 210, 31);

        jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getSize()+6f));
        jLabel2.setText(bundle.getString("CISocketportOptions.jLabel2.text")); 
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 240, 200, 23);

        jTextField1.setFont(jTextField1.getFont().deriveFont(jTextField1.getFont().getSize()+6f));
        getContentPane().add(jTextField1);
        jTextField1.setBounds(240, 240, 70, 30);

        jLabel3.setFont(jLabel3.getFont().deriveFont(jLabel3.getFont().getSize()+6f));
        jLabel3.setText(bundle.getString("CISocketportOptions.jLabel3.text")); 
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 270, 200, 23);

        jTextField2.setFont(jTextField2.getFont().deriveFont(jTextField2.getFont().getSize()+6f));
        getContentPane().add(jTextField2);
        jTextField2.setBounds(240, 270, 70, 30);

        jLabel4.setFont(jLabel4.getFont().deriveFont(jLabel4.getFont().getSize()+6f));
        jLabel4.setText(bundle.getString("CISocketportOptions.jLabel4.text")); 
        getContentPane().add(jLabel4);
        jLabel4.setBounds(320, 270, 240, 23);

        jButton1.setFont(jButton1.getFont().deriveFont(jButton1.getFont().getSize()+12f));
        jButton1.setText(bundle.getString("CISocketportOptions.jButton1.text")); 
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(100, 350, 120, 40);

        jButton2.setFont(jButton2.getFont().deriveFont(jButton2.getFont().getSize()+12f));
        jButton2.setText(bundle.getString("CISocketportOptions.jButton2.text")); 
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(260, 350, 130, 40);

        jTextField3.setFont(jTextField3.getFont().deriveFont(jTextField3.getFont().getSize()+6f));
        getContentPane().add(jTextField3);
        jTextField3.setBounds(240, 170, 210, 29);

        jTextField4.setFont(jTextField4.getFont().deriveFont(jTextField4.getFont().getSize()+6f));
        getContentPane().add(jTextField4);
        jTextField4.setBounds(240, 200, 210, 29);

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setFont(jRadioButton5.getFont().deriveFont(jRadioButton5.getFont().getSize()+6f));
        jRadioButton5.setText(bundle.getString("CISocketportOptions.jRadioButton5.text")); 
        getContentPane().add(jRadioButton5);
        jRadioButton5.setBounds(30, 110, 230, 31);

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setFont(jRadioButton6.getFont().deriveFont(jRadioButton6.getFont().getSize()+6f));
        jRadioButton6.setText(bundle.getString("CISocketportOptions.jRadioButton6.text")); 
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton6);
        jRadioButton6.setBounds(30, 140, 210, 31);

        jTextField5.setFont(jTextField5.getFont().deriveFont(jTextField5.getFont().getSize()+6f));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(260, 110, 190, 30);

        jTextField6.setFont(jTextField6.getFont().deriveFont(jTextField6.getFont().getSize()+6f));
        getContentPane().add(jTextField6);
        jTextField6.setBounds(240, 300, 170, 30);

        jLabel5.setFont(jLabel5.getFont().deriveFont(jLabel5.getFont().getSize()+6f));
        jLabel5.setText(bundle.getString("CISocketportOptions.jLabel5.text")); 
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 300, 200, 30);

        pack();
    }

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
  setVisible(false);
}

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {

   String conf[]=instrument.wn.w.csvLineToArray(instrument.nodeMgntPanel2.socketportConfig);
   if(conf.length<10) {conf=new String[10]; for(int i=0;i<conf.length;i++) conf[i]="";}
   conf[1]=jTextField1.getText().trim();
   if(conf[1].length()<1 || !instrument.wn.isNumeric(conf[1])) conf[1]="1";
   conf[2]=jTextField2.getText().trim();
   if(conf[2].length()<1 || !instrument.wn.isNumeric(conf[2])) conf[2]="60";
   if(jRadioButton1.isSelected()) conf[5]="0";
   else if(jRadioButton2.isSelected()) conf[5]="1";
   else if(jRadioButton3.isSelected()) {conf[5]="2"; conf[6]=jTextField3.getText().trim();}
   else if(jRadioButton4.isSelected()) {conf[5]="3"; conf[6]=jTextField4.getText().trim();}
   else if(jRadioButton5.isSelected()) {conf[5]="5"; conf[6]=jTextField5.getText().trim();}
   else if(jRadioButton6.isSelected()) conf[5]="7";
   conf[9]=jTextField6.getText(); 
   conf[9]=instrument.wn.w.replace(conf[9],",",".");
   if(conf[9].length()==0) {conf[9]=".";  jTextField6.setText(conf[9]);}
   String contCmd="performcommand wsn.WSN setsocketportconfig "+instrument.nodeMgntPanel2.jLabel21.getText().trim()+" "+instrument.wn.w.arrayToCsvLine(conf) +" null null null null null null null null 0 0 0 0 ? ? ? 0";
   instrument.wn.w.sendToOne(contCmd,instrument.wn.getItemId((String)instrument.nodeMgntPanel2.jList3.getSelectedValue()));
   setVisible(false);
}

private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {

}

private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {

}

    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;

}