
package ci;

import golib.Config;
import golib.Status;
import java.awt.Color;
import java.awt.Toolkit;
import java.util.Properties;
import java.util.TreeMap;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;
import y.ylib.OneVar;

/**
 *
 * @author peter
 */
public class HistoryGraphSetup extends javax.swing.JDialog {

    DataViewFrame dFrame;
    Properties originalProps;
    CrInstrument instrument;
    public HistoryGraphSetup(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        instrument=(CrInstrument)parent;
        dFrame=instrument.dFrame;

        int width=Toolkit.getDefaultToolkit().getScreenSize().width;
        int h=Toolkit.getDefaultToolkit().getScreenSize().height-20;

        int w2=540;
        int h2=420;

        setSize(w2,h2);

        setTitle("Graph Setup");

        setLocation((width-w2)/2,(h-h2)/2-10);

        java.awt.Image iconImage = new ImageIcon(getClass().getClassLoader().getResource("cr_instrument_t.gif")).getImage();
    setIconImage(iconImage);
        init();
    }
    void init(){
        jRadioButton1.setSelected(dFrame.instrument.getPropsInt("history_linetype")==1);
        jRadioButton2.setSelected(dFrame.instrument.getPropsInt("history_linetype")==2);
        jComboBox1.setSelectedItem(dFrame.instrument.getPropsString("history_linesize"));
        jComboBox2.setSelectedItem(dFrame.instrument.getPropsString("history_pointsize"));
        jRadioButton3.setSelected(dFrame.instrument.getPropsInt("history_bgtype")==1);
        jRadioButton4.setSelected(dFrame.instrument.getPropsInt("history_bgtype")==2);
        jLabel2.setBackground(new Color(dFrame.instrument.getPropsInt("history_bgcolor")));
        jLabel3.setBackground(new Color(dFrame.instrument.getPropsInt("history_gcolor1")));
        jLabel5.setBackground(new Color(dFrame.instrument.getPropsInt("history_gcolor2")));
        originalProps=(Properties)dFrame.instrument.props.clone();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jComboBox2 = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("ci/Bundle"); 
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)), bundle.getString("HistoryGraphSetup.jPanel1.border.title"))); 
        jPanel1.setLayout(null);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText(bundle.getString("HistoryGraphSetup.jRadioButton1.text")); 
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", " ", " " }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jPanel3.add(jComboBox1);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(30, 20, 290, 31);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText(bundle.getString("HistoryGraphSetup.jRadioButton2.text")); 
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton2);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        jPanel4.add(jComboBox2);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(30, 53, 280, 33);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 10, 470, 90);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)), bundle.getString("HistoryGraphSetup.jPanel2.border.title"))); 
        jPanel2.setLayout(null);

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setText(bundle.getString("HistoryGraphSetup.jRadioButton3.text")); 
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jRadioButton3);

        jLabel2.setBackground(new java.awt.Color(255, 204, 255));
        jLabel2.setOpaque(true);
        jLabel2.setPreferredSize(new java.awt.Dimension(40, 25));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel2);

        jPanel2.add(jPanel5);
        jPanel5.setBounds(30, 25, 390, 35);

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setSelected(true);
        jRadioButton4.setText(bundle.getString("HistoryGraphSetup.jRadioButton4.text")); 
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        jPanel6.add(jRadioButton4);

        jLabel3.setBackground(new java.awt.Color(255, 204, 255));
        jLabel3.setOpaque(true);
        jLabel3.setPreferredSize(new java.awt.Dimension(40, 25));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel3);

        jLabel4.setText(bundle.getString("HistoryGraphSetup.jLabel4.text")); 
        jPanel6.add(jLabel4);

        jLabel5.setBackground(new java.awt.Color(255, 204, 255));
        jLabel5.setOpaque(true);
        jLabel5.setPreferredSize(new java.awt.Dimension(40, 25));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel5);

        jPanel2.add(jPanel6);
        jPanel6.setBounds(30, 60, 360, 35);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(30, 110, 470, 100);

        jButton1.setText(bundle.getString("HistoryGraphSetup.jButton1.text")); 
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(130, 260, 90, 23);

        jButton2.setText(bundle.getString("HistoryGraphSetup.jButton2.text")); 
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(260, 260, 90, 23);

        pack();
    }

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {
      updateSetup();
    }

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {
        Color newColor = JColorChooser.showDialog(null, "Choose a color", jLabel2.getBackground());
        if(newColor!=null) {
            jLabel2.setBackground(newColor);
            if(jRadioButton3.isSelected()) updateSetup();
        }
    }

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {
        Color newColor = JColorChooser.showDialog(null, "Choose a color", jLabel3.getBackground());
        if(newColor!=null) {
            jLabel3.setBackground(newColor);
            if(jRadioButton4.isSelected()) updateSetup();
        }
    }

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {
        Color newColor = JColorChooser.showDialog(null, "Choose a color", jLabel5.getBackground());
        if(newColor!=null) {
            jLabel5.setBackground(newColor);
            if(jRadioButton4.isSelected()) updateSetup();
        }
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        reset();
        setVisible(false);
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
       updateSetup();
       setVisible(false);
    }

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {
       updateSetup();
    }

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {
                if(jRadioButton1.isSelected() && evt.getStateChange()==evt.SELECTED){
        updateSetup();
        }
    }

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {
        if(jRadioButton2.isSelected() && evt.getStateChange()==evt.SELECTED){
        updateSetup();
        }
    }

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {
    updateSetup();
    }

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        updateSetup();
    }

    private void formWindowClosing(java.awt.event.WindowEvent evt) {
                reset();
        setVisible(false);
    }
public void reset(){
    dFrame.instrument.props=originalProps;
    init();
    updateSetup();
}
    public void updateSetup(){
    if(jRadioButton1.isSelected()) dFrame.instrument.props.setProperty("history_linetype","1");
            else dFrame.instrument.props.setProperty("history_linetype","2");
    dFrame.instrument.props.setProperty("history_linesize",""+jComboBox1.getSelectedItem());
    dFrame.instrument.props.setProperty("history_pointsize",""+jComboBox2.getSelectedItem());
    if(jRadioButton3.isSelected()) dFrame.instrument.props.setProperty("history_bgtype","1");
            else dFrame.instrument.props.setProperty("history_bgtype","2");
    dFrame.instrument.props.setProperty("history_bgcolor",""+jLabel2.getBackground().getRGB());
    dFrame.instrument.props.setProperty("history_gcolor1",""+jLabel3.getBackground().getRGB());
    dFrame.instrument.props.setProperty("history_gcolor2",""+jLabel5.getBackground().getRGB());

    int inx=0; 
        TreeMap config2s=dFrame.gFrame.multiPanel.configArr[inx];
        TreeMap stat2s=dFrame.gFrame.multiPanel.statusArr[inx];
        Config cfg=(Config)config2s.get("0");
        Status stat=(Status)stat2s.get("0");
        cfg.longValue[0]=(dFrame.instrument.getPropsInt("history_bgtype")==2? OneVar.add(cfg.longValue[0],9):OneVar.remove(cfg.longValue[0],9));
        cfg.intValue[6]=(dFrame.instrument.getPropsInt("history_linetype")==1? dFrame.instrument.getPropsInt("history_linesize"):0);
        cfg.intValue[7]=(dFrame.instrument.getPropsInt("history_linetype")==2? dFrame.instrument.getPropsInt("history_pointsize"):0);
        cfg.intValue[4]=(dFrame.instrument.getPropsInt("history_linetype")==1? 1:(dFrame.instrument.getPropsInt("history_pointsize")>3? 3:1));
        cfg.c[0]=new Color(dFrame.instrument.getPropsInt("history_bgcolor"));
        cfg.c[60]=new Color(dFrame.instrument.getPropsInt("history_gcolor1"));
        cfg.c[61]=new Color(dFrame.instrument.getPropsInt("history_gcolor2"));

          config2s.put("0", cfg);
         if(dFrame.gFrame.multiPanel.panels.length>inx) dFrame.gFrame.multiPanel.setConfig(inx, config2s);

          dFrame.gFrame.showCurve();
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistoryGraphSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistoryGraphSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistoryGraphSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistoryGraphSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HistoryGraphSetup dialog = new HistoryGraphSetup(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;

}