
package ci;

import java.awt.Color;
import java.awt.Toolkit;
import java.util.ResourceBundle;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import y.base64.YB642D;
import y.ende2003.d2003;

/**
 *
 * @author Administrator
 */
public class MgntDialog extends javax.swing.JDialog {

    CrInstrument instrument;
    private ResourceBundle bundle2 = java.util.ResourceBundle.getBundle("ci/Bundle");
    public MgntDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         this.instrument=(CrInstrument)parent;
         int width=Toolkit.getDefaultToolkit().getScreenSize().width;
        int h=Toolkit.getDefaultToolkit().getScreenSize().height-20;

        int w2=450;
        int h2=120;

        setSize(w2,h2);

        setLocation((width-w2)/2,(h-h2)/2);

        setIconImage(instrument.iconImage);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("ci/Bundle"); 
        setTitle(bundle.getString("MgntDialog.title")); 
        getContentPane().setLayout(null);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setFont(new java.awt.Font("·s²Ó©úÅé", 0, 18)); 
        jLabel1.setText(bundle.getString("MgntDialog.jLabel1.text")); 
        jPanel1.add(jLabel1);

        jPasswordField1.setFont(jPasswordField1.getFont().deriveFont(jPasswordField1.getFont().getSize()+6f));
        jPasswordField1.setPreferredSize(new java.awt.Dimension(156, 30));
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField1);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 420, 50);

        pack();
    }

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {
       String pw=new String(jPasswordField1.getPassword());
       if(d2003.de(pw, instrument.props.getProperty("mgnt-pw")).equals(pw)) {

           jPasswordField1.setText("");
           setVisible(false); 
           instrument.jTabbedPane1.add("Admin",instrument.jPanel3);
           instrument.jTabbedPane1.setSelectedComponent(instrument.jPanel3);
           instrument.adminLogin=true;
           instrument.menuItemLoginAdmin.setEnabled(false);
           instrument.menuItemLoginUser.setEnabled(false);
           instrument.updateTitle();
       }
       else JOptionPane.showMessageDialog(this, bundle2.getString("CrInstrument.xy.msg104"));
    }

    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;

}