
package ci;

import java.awt.Color;
import java.awt.Toolkit;
import java.util.ResourceBundle;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import y.base64.YB642D;
import y.ende2003.d2003;

/**
 *
 * @author Administrator
 */
public class MgntDialog extends javax.swing.JDialog {

    CrInstrument pro;
    private ResourceBundle bundle2 = java.util.ResourceBundle.getBundle("ci/Bundle");
    public MgntDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         this.pro=(CrInstrument)parent;
         int width=Toolkit.getDefaultToolkit().getScreenSize().width;
        int h=Toolkit.getDefaultToolkit().getScreenSize().height-20;

        int w2=350;
        int h2=120;

        setSize(w2,h2);

        setLocation((width-w2)/2,(h-h2)/2);

        setIconImage(pro.iconImage);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("ci/Bundle"); 
        setTitle(bundle.getString("MgntDialog.title")); 
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("新細明體", 0, 18)); 
        jLabel1.setText(bundle.getString("MgntDialog.jLabel1.text")); 
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 10, 130, 40);

        jPasswordField1.setFont(new java.awt.Font("新細明體", 0, 18)); 
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(150, 20, 160, 30);

        pack();
    }

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {
       String pw=new String(jPasswordField1.getPassword());
       if(d2003.de(pw, pro.props.getProperty("mgnt-pw")).equals(pw)) {

           jPasswordField1.setText("");
           setVisible(false); 
           pro.jTabbedPane1.add("Admin",pro.jPanel3);
           pro.jTabbedPane1.setSelectedComponent(pro.jPanel3);
           pro.adminLogin=true;
           pro.menuItemLoginAdmin.setEnabled(false);
           pro.menuItemLoginUser.setEnabled(false);
           pro.updateTitle();
       }
       else JOptionPane.showMessageDialog(this, bundle2.getString("CrInstrument.xy.msg104"));
    }

    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;

}