
package ci;

import java.awt.Toolkit;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Date;
import java.util.Iterator;
import java.util.TreeMap;
import javax.swing.ImageIcon;

/**
 *
 * @author peter
 */
public class Statistical extends javax.swing.JDialog {

    DataViewFrame dFrame;
    CrInstrument instrument;
    NumberFormat numberFormat = new DecimalFormat("######################0.0################################################");
    public Statistical(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        instrument=((CrInstrument)parent);
        dFrame=instrument.dFrame;
        initComponents();
        int width=Toolkit.getDefaultToolkit().getScreenSize().width;
        int h=Toolkit.getDefaultToolkit().getScreenSize().height-20;

        int w2=600;
        int h2=320;

        setSize(w2,h2);

        setTitle("Data Summary");

        setLocation((width-w2)/2,(h-h2)/2-10);

        java.awt.Image iconImage = new ImageIcon(getClass().getClassLoader().getResource("cr_instrument_t.gif")).getImage();
    setIconImage(iconImage);
    }
public void setPlace(int col){
    if(dFrame.dataDTM==null || dFrame.dataDTM.length<1){
          jTextField3.setText("");
          jTextField4.setText("");
          jTextField5.setText("");
          jTextField6.setText("");
          jTextField2.setText("");
          jTextField7.setText("");
          jTextField1.setText("");
          return;
    }
    setTitle("Selection Summary: "+dFrame.dataTitle[col]);
    TreeMap dataTM=dFrame.dataDTM[col];
    Iterator it=dataTM.keySet().iterator();
    boolean first=true;
    long firstTime=0,lastTime=0,count=0;
    double max=0.0,min=0.0,average=0.0,std=0.0,sum=0.0;
    for(;it.hasNext();){
        long key=((Long)it.next()).longValue();
        double v=((Double)dataTM.get(new Long(key))).doubleValue();
        if(first) {
         firstTime=key;
         max=v;
         min=v;
         first=false;
        } else {
            if(v>max) max=v;
            if(min>v) min=v;
        }
        sum += v;
        count++;
        lastTime=key;
      }
      if(count>0) {
          average=sum/((double)count);
          average=((double)Math.round(average* 10000.0))/10000.0;
          if(count>1){
            it=dataTM.values().iterator();
            double sumSqr=0.0;
            for(;it.hasNext();){
              double v=((Double)it.next()).doubleValue();
              sumSqr=sumSqr+(v-average)*(v-average);
            }
            std=Math.sqrt(sumSqr/((double)(count-1)));
            std=((double)Math.round(std* 1000000.0))/1000000.0;
          }
          jTextField3.setText(dFrame.format4.format(new Date(firstTime)));
          jTextField4.setText(dFrame.format4.format(new Date(lastTime)));
          jTextField5.setText(""+count);
          jTextField6.setText(numberFormat.format(max));
          jTextField2.setText(numberFormat.format(min));
          jTextField7.setText(numberFormat.format(average));
          jTextField1.setText(numberFormat.format(std));
        }
      else {
          jTextField3.setText("");
          jTextField4.setText("");
          jTextField5.setText("");
          jTextField6.setText("");
          jTextField2.setText("");
          jTextField7.setText("");
          jTextField1.setText("");
      }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("ci/Bundle"); 
        setTitle(bundle.getString("Statistical.title")); 
        getContentPane().setLayout(null);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel3.setText(bundle.getString("Statistical.jLabel3.text")); 
        jPanel1.add(jLabel3);

        jTextField1.setPreferredSize(new java.awt.Dimension(156, 25));
        jPanel1.add(jTextField1);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 220, 360, 40);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel2.setText(bundle.getString("Statistical.jLabel2.text")); 
        jPanel2.add(jLabel2);

        jTextField2.setPreferredSize(new java.awt.Dimension(156, 25));
        jPanel2.add(jTextField2);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(20, 140, 370, 40);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText(bundle.getString("Statistical.jLabel1.text")); 
        jPanel3.add(jLabel1);

        jTextField6.setPreferredSize(new java.awt.Dimension(156, 26));
        jPanel3.add(jTextField6);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(20, 100, 400, 40);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel5.setText(bundle.getString("Statistical.jLabel5.text")); 
        jPanel4.add(jLabel5);

        jTextField3.setPreferredSize(new java.awt.Dimension(156, 25));
        jPanel4.add(jTextField3);

        jLabel6.setText(bundle.getString("Statistical.jLabel6.text")); 
        jPanel4.add(jLabel6);

        jTextField4.setPreferredSize(new java.awt.Dimension(156, 25));
        jPanel4.add(jTextField4);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(20, 20, 540, 40);

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel4.setText(bundle.getString("Statistical.jLabel4.text")); 
        jPanel5.add(jLabel4);

        jTextField5.setPreferredSize(new java.awt.Dimension(146, 25));
        jPanel5.add(jTextField5);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(20, 60, 460, 35);

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel7.setText(bundle.getString("Statistical.jLabel7.text")); 
        jPanel6.add(jLabel7);

        jTextField7.setPreferredSize(new java.awt.Dimension(156, 25));
        jPanel6.add(jTextField7);

        getContentPane().add(jPanel6);
        jPanel6.setBounds(20, 180, 550, 35);

        pack();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Statistical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Statistical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Statistical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Statistical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Statistical dialog = new Statistical(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;

}