
package ci;

import java.awt.Color;
import java.awt.Toolkit;
import java.util.ResourceBundle;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import y.base64.YB642D;
import y.ende2003.d2003;

/**
 *
 * @author Administrator
 */
public class UserDialog extends javax.swing.JDialog {

    CrInstrument pro;
    private ResourceBundle bundle2 = java.util.ResourceBundle.getBundle("ci/Bundle");
    public UserDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         this.pro=(CrInstrument)parent;
         int width=Toolkit.getDefaultToolkit().getScreenSize().width;
        int h=Toolkit.getDefaultToolkit().getScreenSize().height-20;

        int w2=350;
        int h2=120;

        setSize(w2,h2);

        setLocation((width-w2)/2,(h-h2)/2);

        setIconImage(pro.iconImage);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("ci/Bundle"); 
        setTitle(bundle.getString("UserDialog.title")); 
        getContentPane().setLayout(null);

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getSize()+6f));
        jLabel1.setText(bundle.getString("UserDialog.jLabel1.text")); 
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 10, 130, 40);

        jPasswordField1.setFont(jPasswordField1.getFont().deriveFont(jPasswordField1.getFont().getSize()+6f));
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(160, 20, 150, 30);

        pack();
    }

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {
       String pw=new String(jPasswordField1.getPassword());

       if(YB642D.decode(pro.props.getProperty("setting-pw")).equals(pw)) {
           jPasswordField1.setText("");
           setVisible(false); 
           pro.userLogin=true;
           pro.btnLogoutUser.setVisible(true);
           pro.jPanel28.setVisible(true);
           pro.menuItemLoginUser.setEnabled(false);
           pro.updateTitle();
       }
       else JOptionPane.showMessageDialog(this, bundle2.getString("CrInstrument.xy.msg105"));
    }

    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;

}